import { config as reactInternalConfig } from "@repo/eslint-config/react-internal";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...reactInternalConfig,
  {
    // `worker-configuration.d.ts` is auto-generated by `wrangler types` and
    // gitignored — eslint should not scan it. The file's eslint-disable
    // directive becomes "unused" because the actual lint problem it suppresses
    // already passes; the directive only exists for older wrangler-types outputs.
    ignores: ["worker-configuration.d.ts"],
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: ["@tauri-apps/*"],
          paths: [
            {
              name: "@repo/plugin-console",
              message: "Use @repo/plugin-console/web to avoid desktop-only transitive imports in apps/web.",
            },
            {
              name: "@repo/web-auth-device-session",
              message: "Use @repo/web-auth-device-session/web to keep apps/web on browser-safe exports.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
      },
    },
  },
];
