import React from 'react';
import {createRoot} from 'react-dom/client';
import {createBrowserRouter,RouterProvider} from 'react-router';
import {accountScope,generationMarkerKey} from './packages/plugin-web-storage/src/index';
import {WebShellProvider} from './packages/xai-web-shell/src/index';
import {webShellModuleRegistrations} from './apps/web/src/routes/modules/shellRegistrations';
import {requestSettingsDeparture} from './apps/web/src/routes/modules/settingsDeparture';
import './packages/plugin-web-tokens/src/tokens.css';
import './packages/plugin-web-tokens/src/layout.css';
import './packages/plugin-web-pomodoro/src/styles.css';
const owner='pomo-departure-native';localStorage.setItem(generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');
const defaults={preset:'focus-25',custom_minutes:45,display_style:'apple',theme:'coral',sound:'soft-chime',muted:false};
for(const [suffix,value] of Object.entries(defaults))localStorage.setItem('xai_pref_pomodoro_'+suffix,JSON.stringify(value));
const nativeSet=Storage.prototype.setItem;
const registration=webShellModuleRegistrations.find(r=>r.moduleId==='pomodoro')!;const Module=registration.children.find(r=>r.path==='')!.render;
history.replaceState(null,'','/app/pomodoro');const router=createBrowserRouter([{path:'/app/pomodoro',element:<Module/>},{path:'/app/dashboard',element:<div>Dashboard destination</div>}]);
(window as any).verify={deny(){Storage.prototype.setItem=function(k,v){if(k==='xai_pref_pomodoro_theme')throw new DOMException('quota','QuotaExceededError');nativeSet.call(this,k,v)}},router,signoutResult:'unresolved',signout(){void requestSettingsDeparture('sign-out').then(x=>{(window as any).verify.signoutResult=x})}};
createRoot(document.getElementById('app')!).render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);
