import React from './packages/plugin-web-storage/node_modules/react/index.js';import {createRoot} from './packages/plugin-web-storage/node_modules/react-dom/client.js';
import {AccountDataGate,requestAccountDataManagement} from './packages/plugin-web-storage/src/AccountDataGate.tsx';import {accountScope,createScopedStorage} from './packages/plugin-web-storage/src/internal/accountScope.ts';import {readGeneration} from './packages/plugin-web-storage/src/internal/accountMigration.ts';import {aiKeyStorage,aiSecretMigrationParticipant} from './packages/plugin-web-ai-chat/src/internal/secretStore.ts';import {webShellModuleRegistrations} from './apps/web/src/routes/modules/shellRegistrations';
import './packages/plugin-web-storage/src/AccountDataGate.css';
const assert=(v:any,m:string)=>{if(!v)throw Error(m)};const delay=()=>new Promise(r=>setTimeout(r,100));const root=createRoot(document.getElementById('app')!);const reads:string[]=[];
function Content(){const current=createScopedStorage(localStorage);const raw=current.getItem('xai_task_cols')??current.getItem('xai_pref_custom_private');reads.push(raw??'empty');return <p data-private>{raw??'empty'}</p>}
function show(accountId:string,authenticated=true){root.render(<AccountDataGate accountId={accountId} authenticated={authenticated} secrets={aiSecretMigrationParticipant}><Content/></AccountDataGate>)}
async function click(text:string){for(let i=0;i<100;i++){const button=[...document.querySelectorAll('button')].find(e=>e.textContent===text&&!e.disabled);if(button){button.click();await delay();return}await delay()}throw Error('button missing '+text)}
async function run(){assert(webShellModuleRegistrations.length>=14,'host graph');const cols=(title:string)=>JSON.stringify(['overdue','next7','later','nodate'].map((id,i)=>({id,key:['overdue','next_7_days','later','no_date'][i],tasks:i===3?[{id:'one',title:{en:title,zh:title}}]:[],completed:[],count:i===3?1:0})));const legacy='  '+cols('UNOWNED')+'\n';localStorage.setItem('xai_task_cols',legacy);localStorage.setItem('xai_unknown_legacy','broken original');localStorage.setItem('xai_theme','dark');accountScope.lock();show('A');await delay();assert(reads.length===0,'private subtree before consent');assert([...document.querySelectorAll('input[type=checkbox]')].every((x:any)=>!x.checked),'migration not opt in');await click('Decide later');assert(reads.length===0,'later leaked private tree');await click('Start without importing');await click('Continue to workspace');assert(reads.at(-1)==='empty','empty imported legacy');createScopedStorage(localStorage).setItem('xai_pref_custom_private','A PRIVATE');await aiKeyStorage.saveKey('deepseek','synthetic-owned-A');const before=readGeneration(localStorage,'A')!.generation;
 requestAccountDataManagement();await delay();const box=[...document.querySelectorAll('label')].find(e=>e.textContent?.includes('Tasks and boards'))!.querySelector('input')!;box.click();await click('Import selected data');for(let i=0;i<100&&document.querySelector('#account-data-title')?.textContent!=='Your choice is saved';i++)await delay();assert(readGeneration(localStorage,'A')!.generation!==before,'import did not publish: '+document.querySelector('#app')?.textContent);assert(!document.querySelector('[data-private]'),'published before continue');await click('Undo this import');assert(readGeneration(localStorage,'A')!.generation===before,'rollback did not restore prior');await click('Continue to workspace');assert(reads.at(-1)==='A PRIVATE','rollback lost original owner content');assert(await aiKeyStorage.loadKey('deepseek')==='synthetic-owned-A','rollback lost owner key');const old=createScopedStorage(localStorage);show('A',false);await delay();assert(!document.querySelector('[data-private]'),'signed out content remains');let signedOutKey;try{signedOutKey=await aiKeyStorage.loadKey('deepseek')}catch{}assert(signedOutKey!=='synthetic-owned-A','signed out reads key');show('B');await delay();assert(!document.querySelector('[data-private]'),'A stayed mounted for B');let rejected=false;try{old.setItem('xai_task_cols','bad')}catch{rejected=true}assert(rejected,'old writer');await click('Start without importing');await click('Continue to workspace');assert(reads.at(-1)==='empty','B read A');assert(await aiKeyStorage.loadKey('deepseek')===null,'B read A key');assert(localStorage.getItem('xai_theme')==='dark','device preference changed');assert(localStorage.getItem('xai_task_cols')===legacy&&localStorage.getItem('xai_unknown_legacy')==='broken original','legacy lost');return {pass:true,checks:['default opt-in','decide later no mount','empty choice','actual selected import','actual undo to previous generation','A key retained','B no A content/key','stale callback revoked','device and originals retained']}}
run().then(result=>{(window as any).nativeResult={status:'PASS',...result}}).catch(error=>{(window as any).nativeResult={status:'FAIL',error:error.stack}});
