/** Explicit local ownership. Prefixes and registry categories are not security boundaries. */
export type LocalOwnership = "account" | "device";
export const LOCAL_KEY_OWNERSHIP: Readonly<Record<string, LocalOwnership>> = Object.freeze({
  "xai:web:observability-consent": "device",
  "xai_accent_hue": "device",
  "xai_active_board": "account",
  "xai_ai_base_url": "account",
  "xai_ai_convos": "account",
  "xai_ai_insights": "device",
  "xai_ai_model_default": "account",
  "xai_ai_provider": "account",
  "xai_ai_streaming": "device",
  "xai_ai_voice": "device",
  "xai_bg_tone": "device",
  "xai_bk_calendar_mode": "device",
  "xai_bk_dash_order": "device",
  "xai_bk_dash_split": "device",
  "xai_bk_state_v2": "account",
  "xai_bk_view": "device",
  "xai_board_filter_by_id": "account",
  "xai_board_inbox": "account",
  "xai_board_panels": "account",
  "xai_board_view_by_id": "account",
  "xai_board_workspaces": "account",
  "xai_boards_v2": "account",
  "xai_calendar_events": "account",
  "xai_calendar_view": "device",
  "xai_clock_style": "device",
  "xai_clock_tz": "device",
  "xai_countdowns": "account",
  "xai_dash_order": "device",
  "xai_dashboard_stickies": "account",
  "xai_dashboard_weather": "account",
  "xai_habits_state": "account",
  "xai_matrix_state": "account",
  "xai_meditation_prefs": "account",
  "xai_metric_tracker_state_v1": "account",
  "xai_pet_id": "device",
  "xai_pet_pos": "device",
  "xai_pomodoro_sessions": "account",
  "xai_pref_collab_default_share": "account",
  "xai_pref_collab_mention_notify": "device",
  "xai_pref_collab_show_avatars": "device",
  "xai_pref_dashboard_header_note": "account",
  "xai_pref_dashboard_header_note_x": "device",
  "xai_pref_density": "device",
  "xai_pref_dt_holidays": "device",
  "xai_pref_dt_lunar": "device",
  "xai_pref_dt_start_week": "device",
  "xai_pref_dt_timezone": "device",
  "xai_pref_dt_week_numbers": "device",
  "xai_pref_features_board": "device",
  "xai_pref_features_calendar": "device",
  "xai_pref_features_dashboard": "device",
  "xai_pref_features_habits": "device",
  "xai_pref_features_matrix": "device",
  "xai_pref_features_meditation": "device",
  "xai_pref_features_pomodoro": "device",
  "xai_pref_features_tasks": "device",
  "xai_pref_font_scale": "device",
  "xai_pref_integrations_connected_gcal": "account",
  "xai_pref_integrations_connected_linear": "account",
  "xai_pref_integrations_connected_notion": "account",
  "xai_pref_lang": "device",
  "xai_pref_more_add_to": "device",
  "xai_pref_more_date_recognition": "device",
  "xai_pref_more_default_date": "device",
  "xai_pref_more_default_list": "account",
  "xai_pref_more_default_pri": "device",
  "xai_pref_more_default_rem_all": "device",
  "xai_pref_more_default_rem_due": "device",
  "xai_pref_more_default_tag": "account",
  "xai_pref_more_launch_at_login": "device",
  "xai_pref_more_minimize_on_launch": "device",
  "xai_pref_more_overdue_at": "device",
  "xai_pref_more_remove_date_text": "device",
  "xai_pref_more_remove_tags": "device",
  "xai_pref_more_url_parse": "device",
  "xai_pref_more_win_type": "device",
  "xai_pref_notif_done_sound": "device",
  "xai_pref_notif_enabled": "device",
  "xai_pref_notif_push_habit": "device",
  "xai_pref_notif_push_pomo": "device",
  "xai_pref_notif_push_task": "device",
  "xai_pref_notif_quiet": "device",
  "xai_pref_notif_quiet_end": "device",
  "xai_pref_notif_quiet_start": "device",
  "xai_pref_pomodoro_custom_minutes": "device",
  "xai_pref_pomodoro_display_style": "device",
  "xai_pref_pomodoro_muted": "device",
  "xai_pref_pomodoro_preset": "device",
  "xai_pref_pomodoro_sound": "device",
  "xai_pref_pomodoro_theme": "device",
  "xai_pref_premium_started_at": "account",
  "xai_pref_premium_tier": "account",
  "xai_pref_smart_lists": "account",
  "xai_pref_sticky_color": "device",
  "xai_pref_sticky_font": "device",
  "xai_pref_sticky_grid_spacing": "device",
  "xai_pref_sticky_pin_default": "device",
  "xai_pref_sticky_restore_size": "device",
  "xai_pref_theme": "device",
  "xai_pref_week_start": "device",
  "xai_rail_order": "device",
  "xai_rail_pos": "device",
  "xai_task_cols": "account",
  "xai_tt_categories_v2": "account",
  "xai_tt_category_collapsed_v1": "account",
  "xai_tt_day_records_collapsed_v1": "device",
  "xai_tt_entries_v2": "account",
  "xai_tt_insights_v1": "account",
  "xai_tt_mode": "device",
  "xai_tt_sidebar_insights_hidden_v1": "device",
  "xai_tt_time_status_cards_v1": "device",
  "xai_tt_time_status_custom_cards_v1": "account",
  "xai_tt_time_status_hidden_v1": "device",
  "xai_zones": "account",
 });

export function ownershipForKey(key: string): LocalOwnership {
  const owner = LOCAL_KEY_OWNERSHIP[key];
  // Preserve the open-ended pref API safely: unknown prefs are private by default.
  if (!owner && /^xai_pref_[^/]+$/.test(key)) return "account";
  if (!owner) throw new Error(`Unclassified local storage key: ${key}`);
  return owner;
}
export const ACCOUNT_LOCAL_KEYS = Object.freeze(Object.keys(LOCAL_KEY_OWNERSHIP).filter(key => LOCAL_KEY_OWNERSHIP[key] === "account"));
