import React from 'react';
import {it,expect,vi,beforeEach} from 'vitest';
import {transferableAbortController} from 'node:util';
import {act,cleanup,fireEvent,render,within} from '@testing-library/react';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider} from '@repo/xai-web-shell';
import {composedSettingsRegistration} from '../../../apps/web/src/routes/modules/composedSettingsRegistration';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {fixture,key,logical,nativeGet,nativeSet,activate,choose,select,flush,seed,quota,hold} from '../web-d2-smart-lists-astra/fixture';
fixture();
// Match Node Request with a native AbortController; jsdom AbortSignal is a different realm.
beforeEach(()=>{vi.stubGlobal('AbortController',transferableAbortController().constructor);});
const smart='/app/settings/smart_lists',notifications='/app/settings/notifications';
async function host(pending=false){seed('{"extension":"A"}');const Composed=composedSettingsRegistration.children[0]!.render;const router=createMemoryRouter([{path:'/app/settings/*',element:<Composed/>},{path:'/app/dashboard',element:<div>Dashboard route</div>}],{initialEntries:['/app/dashboard',smart],initialIndex:1});const originalNavigate=router.navigate;const ui0=render(<WebShellProvider modules={[composedSettingsRegistration]} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);const ui={...ui0,q:within(ui0.container)};await flush();const failure=pending?null:quota();choose(ui,0,'hide');await flush();return{ui,router,failure,originalNavigate};}
const navigate=async(router:any,to:any)=>{await act(async()=>{await router.navigate(to);});await flush();};
const click=(ui:any,name:RegExp)=>fireEvent.click(ui.q.getByRole('button',{name}));
it('wrapped route replays object search hash state and replace options exactly',async()=>{const {ui,router}=await host();const state={origin:'first'};await act(async()=>{await router.navigate({pathname:notifications,search:'?first=1',hash:'#section'},{replace:true,state,preventScrollReset:true});});await flush();expect(router.state.location.pathname).toBe(smart);click(ui,/Discard local changes and leave/);await flush();expect(router.state.location).toMatchObject({pathname:notifications,search:'?first=1',hash:'#section',state});expect(router.state.historyAction).toBe('REPLACE');expect(router.state.preventScrollReset).toBe(true);await navigate(router,-1);expect(router.state.location.pathname).toBe('/app/dashboard');});
it('wrapped route retains fromRouteId and relative route resolution',async()=>{const {ui,router}=await host();const plain=createMemoryRouter([{path:'/app/settings/*',element:<div/>}],{initialEntries:[smart]});const options={fromRouteId:plain.routes[0]!.id,relative:'route' as const};await plain.navigate('notifications',options);expect(plain.state.location.pathname).toBe('/app/settings/smart_lists/notifications');await act(async()=>{await router.navigate('notifications',options);});await flush();click(ui,/Discard local changes and leave/);await flush();expect(router.state.location.pathname).toBe(plain.state.location.pathname);plain.dispose();});
it('wrapped numeric POP ignores a later push and retains Forward history',async()=>{const {ui,router}=await host();await act(async()=>{void router.navigate(-1);void router.navigate(notifications);});await flush();click(ui,/Discard local changes and leave/);await flush();expect(router.state.location.pathname).toBe('/app/dashboard');await navigate(router,1);expect(router.state.location.pathname).toBe(smart);});
it('wrapper permits nonparticipant navigation and restores original router method on unmount',async()=>{const {ui,router,originalNavigate}=await host();expect(router.navigate).not.toBe(originalNavigate);await navigate(router,notifications);click(ui,/Discard local changes and leave/);await flush();await navigate(router,'/app/settings/date_time');expect(router.state.location.pathname).toBe('/app/settings/date_time');expect(ui.q.queryByRole('dialog')).toBeNull();ui.unmount();expect(router.navigate).toBe(originalNavigate);await router.navigate('/app/dashboard',{state:{after:'dispose'}});expect(router.state.location.state).toEqual({after:'dispose'});});
it('newer map queued after pending old save keeps original departure guarded until latest succeeds',async()=>{const release=await hold();const {ui,router}=await host(true);await navigate(router,notifications);choose(ui,1,'hide');await flush();const failure=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key&&JSON.parse(v).today==='hide')throw Error('latest quota');nativeSet.call(this,k,v);});await release();await flush();expect(router.state.location.pathname).toBe(smart);expect(ui.q.queryByRole('dialog')).not.toBeNull();expect(select(ui,1).value).toBe('hide');expect(JSON.parse(nativeGet.call(localStorage,key)!)).toEqual({extension:'A',all:'hide'});failure.mockRestore();fireEvent.click(ui.q.getByRole('button',{name:/^Retry$/}));await flush();expect(router.state.location.pathname).toBe(notifications);expect(JSON.parse(nativeGet.call(localStorage,key)!)).toEqual({extension:'A',all:'hide',today:'hide'});});
