import React from 'react';
import {createRoot} from 'react-dom/client';
import {accountScope,generationMarkerKey} from './packages/plugin-web-storage/src/index';
import {createBrowserRouter,RouterProvider} from 'react-router';
import {WebShellProvider} from './packages/xai-web-shell/src/index';
import {composedSettingsRegistration} from './apps/web/src/routes/modules/composedSettingsRegistration';
import './packages/plugin-web-tokens/src/tokens.css';
import './packages/plugin-web-tokens/src/layout.css';
import './packages/plugin-web-settings-shell/src/styles.css';
import './packages/plugin-web-settings-rest/src/styles.css';
const owner='collaborate-native';accountScope.activate(accountScope.lock(owner),'g1');localStorage.setItem(generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));
const keys=['xai_pref_collab_show_avatars','xai_pref_collab_mention_notify'];
const nativeSet=Storage.prototype.setItem;const nativeGet=Storage.prototype.getItem;let accountKey=accountScope.physicalKey('xai_pref_collab_default_share');
(window as any).verify={keys,attempts:[] as string[],deny(){Storage.prototype.setItem=function(k,v){if(keys.includes(k)){(window as any).verify.attempts.push(k);throw new DOMException('quota','QuotaExceededError')}nativeSet.call(this,k,v)}}};
(window as any).verify.readAll=()=>[...keys,accountKey].map(k=>nativeGet.call(localStorage,k));
(window as any).verify.denyThree=()=>{Storage.prototype.setItem=function(k,v){if(keys.includes(k)||k===accountKey)throw new DOMException('quota','QuotaExceededError');nativeSet.call(this,k,v)}};
(window as any).verify.denyAll=()=>{Storage.prototype.getItem=function(){throw new DOMException('denied','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('denied','SecurityError')}};
(window as any).verify.switchOwner=()=>{const next='collaborate-native-b';accountScope.activate(accountScope.lock(next),'g1');nativeSet.call(localStorage,generationMarkerKey(next),JSON.stringify({generation:'g1',migrationId:'fixture-b',previous:null}));accountKey=accountScope.physicalKey('xai_pref_collab_default_share');};
history.replaceState(null,'','/app/settings/collaborate');
const Composed=composedSettingsRegistration.children[0].render;const router=createBrowserRouter([{path:'/app/settings/*',element:<Composed/>}]);
createRoot(document.getElementById('app')!).render(<WebShellProvider modules={[composedSettingsRegistration]} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);
