export type { GridBox, DesktopItem, PersistedLayout, Rect } from './grid';
export type {
  WindowType,
  WindowLabel,
  WindowConfig,
  GridWindowLabel,
  GridWindowRect,
  PluginHostWindowSurface,
  PluginWindowCommandSourceLabel,
  CreateGridWindowInput,
  UpdateGridWindowInput,
  GridWindowSnapshot,
  PluginWindowSnapshot,
  CreatePluginWindowInput,
  UpdatePluginWindowInput,
  ConsoleWindowFrame,
  CommandError,
} from './window';
export type { DroppedFile, EventMap, WebModuleId, WebPreferenceKey, WebPreferenceChange } from './events';
export type {
  PluginManifest,
  PluginInstanceId,
  PluginCenterEntryStatus,
  PluginWindowSurface,
  PluginInstanceLifecycleState,
  PluginInstanceSyncScope,
  PluginInstanceSizePreset,
  PluginInstanceStyleMode,
  PluginInstancePlacement,
  PluginInstanceSize,
  PluginInstanceBehavior,
  PluginInstanceStyle,
  PluginInstanceConfig,
  PluginInstanceConfigInput,
  PluginInstance,
  PluginCenterEntry,
  AddToDesktopRequest,
  PluginComponents,
  PluginRegistration,
  ContentType,
  ConsoleModuleId,
  ConsoleRouteState,
  ConsoleThemeState,
  ConsoleCapabilityStatus,
  ConsoleCapabilityErrorCode,
  ConsoleCapabilityResult,
  ConsoleShortcutBinding,
  ConsoleDownloadRequest,
  ConsoleNotificationRequest,
  ConsoleViewCapabilities,
  ConsoleViewProps,
  ConsoleSidebarEntry,
  ConsoleViewDefinition,
  ConsoleViewRegistration,
  WebModuleRouteProps,
  WebModuleRouteChild,
  WebModuleRouteRegistration,
} from './plugin';
