/** Passive source/effect census installed before dynamic production imports. Explicit component scope only. */
import React from 'react';
import {createRoot} from 'react-dom/client';
type Config={id:string;kind:string;variant:string;lane:string;lang:'en'|'zh';theme?:string;productDensity?:string};
declare global{interface Window{__T06_CONFIG:Config;__T06:any;__visual:any;}}
export const config=window.__T06_CONFIG;
const native={get:Storage.prototype.getItem,set:Storage.prototype.setItem,remove:Storage.prototype.removeItem,clear:Storage.prototype.clear,dispatch:EventTarget.prototype.dispatchEvent,fetch:window.fetch.bind(window),create:URL.createObjectURL.bind(URL),revoke:URL.revokeObjectURL.bind(URL),request:navigator.locks?.request.bind(navigator.locks),lockDescriptor:Object.getOwnPropertyDescriptor(navigator,'locks')};
export function installInstrumentation(){
 const audit:any={phase:'pre-import',ready:false,writes:[],reads:[],events:[],keys:[],downloads:[],urls:[],locks:[],errors:[],dialogs:[],sources:[]};let fault='',taskKey='',scopeAPI:any,held:Promise<any>|null=null,releaseHeld:(()=>void)|null=null;
 const census=()=>Object.fromEntries(Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)).filter((k):k is string=>!!k).sort().map(k=>[k,native.get.call(localStorage,k)]));
 Storage.prototype.getItem=function(key){const r:any={key,phase:audit.phase,fault};audit.reads.push(r);try{if(key===taskKey&&fault==='read')throw Object.assign(Error('induced physical read failure'),{code:'INDUCED_READ'});const value=native.get.call(this,key);r.status='returned';r.value=value;return value;}catch(e){r.status='threw';r.error=String(e);throw e;}};
 Storage.prototype.setItem=function(key,value){const r:any={type:'set',key,value,fault,phase:audit.phase};audit.writes.push(r);if(key===taskKey&&['quota','throw'].includes(fault)){r.status='threw';throw fault==='quota'?new DOMException('T06 quota','QuotaExceededError'):Error('T06 write denied');}native.set.call(this,key,value);r.status='committed';};
 Storage.prototype.removeItem=function(key){audit.writes.push({type:'remove',key,phase:audit.phase});return native.remove.call(this,key);};Storage.prototype.clear=function(){audit.writes.push({type:'clear',phase:audit.phase});return native.clear.call(this);};
 EventTarget.prototype.dispatchEvent=function(event){if(event.type.startsWith('web:'))audit.events.push({type:'bus',channel:event.type,detail:(event as CustomEvent).detail,phase:audit.phase});return native.dispatch.call(this,event);};
 window.fetch=(...args)=>{audit.events.push({type:'fetch',url:String(args[0]),phase:audit.phase});return native.fetch(...args);};
 for(const type of ['keydown','keypress','keyup'])document.addEventListener(type,e=>{const k=e as KeyboardEvent;audit.keys.push({type,key:k.key,shift:k.shiftKey,trusted:k.isTrusted});},true);
 for(const type of ['pointerdown','click','dragstart','drop','dragend'])document.addEventListener(type,e=>audit.events.push({type,trusted:e.isTrusted,target:(e.target as Element)?.outerHTML?.slice(0,160),phase:audit.phase}),true);
 URL.createObjectURL=blob=>{const url=native.create(blob);audit.urls.push({type:'create',url,size:blob.size,mime:blob.type,phase:audit.phase});return url;};URL.revokeObjectURL=url=>{audit.urls.push({type:'revoke',url,phase:audit.phase});return native.revoke(url);};
 const anchorClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download)audit.downloads.push({filename:this.download,href:this.href,phase:audit.phase});return anchorClick.call(this);};
 window.addEventListener('error',e=>audit.errors.push({type:'error',message:e.message,phase:audit.phase}));window.addEventListener('unhandledrejection',e=>audit.errors.push({type:'rejection',message:String(e.reason),phase:audit.phase}));
 for(const name of ['alert','confirm','prompt'] as const){const original=window[name].bind(window) as any;(window as any)[name]=(...args:any[])=>{audit.dialogs.push({name,args,phase:audit.phase});return original(...args);};}
 function restoreLocks(){if(native.lockDescriptor)Object.defineProperty(navigator,'locks',native.lockDescriptor);else delete (navigator as any).locks;}
 return Object.assign(audit,{native,census,setKey(key:string){taskKey=key;},bindScope(value:any){scopeAPI=value;},raw:()=>native.get.call(localStorage,taskKey),scope:()=>scopeAPI?.accountScope.capture(),setPhase(phase:string){audit.phase=phase;},snapshot(){return {raw:native.get.call(localStorage,taskKey),physical:census(),scope:scopeAPI?.accountScope.capture(),writes:[...audit.writes],reads:[...audit.reads],events:[...audit.events],keys:[...audit.keys],urls:[...audit.urls],downloads:[...audit.downloads],locks:[...audit.locks],errors:[...audit.errors],dialogs:[...audit.dialogs],location:location.href,text:document.body.textContent,selected:[...document.querySelectorAll('[data-active="true"]')].map(e=>e.textContent),visibleTasks:[...document.querySelectorAll('.task-card')].map(e=>({text:e.textContent,checkbox:(e.querySelector('.cbx') as Element)?.getAttribute('aria-checked')??e.querySelector('.cbx')?.className})),dialog:[...document.querySelectorAll('[role="dialog"],dialog[open]')].map(e=>e.textContent),success:[...document.querySelectorAll('[role="status"],.toast,.success')].map(e=>e.textContent)};},premount(){const x=this.snapshot();audit.sources.push({phase:'pre-mount',...x});return x;},setFault(value:string){fault=value;},restoreLocks,
 setLockFault(value:string){if(value==='missing-lock')Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});else if(value==='rejected-lock')Object.defineProperty(navigator,'locks',{configurable:true,value:{request:()=>{audit.locks.push({status:'rejected'});return Promise.reject(Error('T06 rejected lock'));}}});else restoreLocks();},
 async hold(){if(!native.request)throw Error('LOCK_ENVIRONMENT');let acquired!:()=>void;const ready=new Promise<void>(r=>{acquired=r;});const wait=new Promise<void>(r=>{releaseHeld=r;});const name=scopeAPI.canonicalDatasetLockName(scopeAPI.accountScope.capture(),'xai_task_cols');held=native.request(name,async()=>{audit.locks.push({name,status:'held'});acquired();await wait;audit.locks.push({name,status:'released'});});await ready;},async release(){releaseHeld?.();releaseHeld=null;await held;held=null;await new Promise(r=>setTimeout(r,200));audit.locks.push({status:'late-settlement-observed'});},
 async newer(){const validate=(await import('../../../packages/xai-web-tasks/src/internal/validate')).isTaskColsArray;return scopeAPI.mutateCanonicalDataset({key:'xai_task_cols',scope:scopeAPI.accountScope.capture(),validate,mutate:(cols:any)=>({ok:true,data:cols.map((c:any)=>({...c,tasks:c.tasks.map((t:any)=>({...t,title:{en:'newer-source',zh:'newer-source'}}))}))})});}
 });
}
export function taskData(variant:string){const task:any={id:'t06-target',title:{en:'t06-target',zh:'t06-target'},priority:'normal',listId:'inbox',tag:'work',tags:['work'],notes:'preserve notes',source:{type:'board-card',boardId:'b1',listId:'bl1',cardId:'bc1'}};if(['normal','dated'].includes(variant)){task.done=true;task.completedAt='2026-09-01T00:00:00Z';}if(variant==='dated')task.dueDate='2026-09-01';if(variant==='stale-date')task.dueDate='1999-01-01';if(variant==='unknown-date')task.dueDate='not-a-date';if(variant==='legacy-false')task.done=false;
 const cols:any[]=['overdue','next7','later','nodate'].map((id,i)=>({id,key:['overdue','next_7_days','later','no_date'][i],count:0,tasks:[]}));if(variant!=='empty'){if(['legacy-missing','legacy-false','undated'].includes(variant))cols[3].completed=[task];else {cols[3].tasks=[task];cols[3].count=1;}}return cols;}
export function rawFor(variant:string){return variant==='corrupt'?'{broken':variant==='legacy'?JSON.stringify(taskData(variant)):JSON.stringify({format:'xai-command-state',version:variant==='unsupported'?999:1,revision:7,data:taskData(variant),receipts:{prior:{operationVersion:1,signature:'prior',result:{ok:true,targetId:'prior'},committedAt:'2026-09-01T00:00:00Z'}}});}
export async function seedAccount(id:string,generation:string,variant:string){const storage=await import('@repo/plugin-web-storage');window.__T06.bindScope(storage);const marker=storage.generationMarkerKey(id);if(native.get.call(localStorage,marker)===null)native.set.call(localStorage,marker,JSON.stringify({generation,migrationId:'t06-explicit-synthetic',previous:null}));
 const prefix='xai:account:v1:'+encodeURIComponent(id)+':'+encodeURIComponent(generation)+':';const key=prefix+'xai_task_cols';if(native.get.call(localStorage,key)===null)native.set.call(localStorage,key,rawFor(variant));const meta=await import('../../../packages/xai-web-tasks/src/internal/taskMeta');for(const [suffix,value] of Object.entries({task_lists:meta.DEFAULT_TASK_LISTS,task_tags:meta.DEFAULT_TASK_TAGS})){const k=prefix+'xai_pref_'+suffix;if(native.get.call(localStorage,k)===null)native.set.call(localStorage,k,JSON.stringify(value));}return key;}
export async function mountModule(){window.__T06=installInstrumentation();const storage=await import('@repo/plugin-web-storage');window.__T06.bindScope(storage);const id='t06-source-control-'+config.id;await seedAccount(id,'g1',config.variant);storage.setCanonicalCommandActivationForTests(true);const scope=storage.accountScope.activate(storage.accountScope.lock(id),'g1');window.__T06.setKey(storage.accountScope.physicalKey('xai_task_cols',scope));if(config.variant==='read')window.__T06.setFault('read');window.__T06.premount();window.__T06.setPhase('mount');const {TasksModule}=await import('@repo/plugin-web-tasks');await import('@repo/plugin-web-tokens');await import('../../../packages/xai-web-tasks/src/styles.css');createRoot(document.getElementById('root')!).render(<TasksModule lang={config.lang}/>);requestAnimationFrame(()=>{window.__T06.ready=true;});}
if(config.lane!=='host'&&config.lane!=='visual')void mountModule();
