import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {act,cleanup,fireEvent,render,waitFor} from '@testing-library/react';
import {accountScope,generationMarkerKey} from '@repo/plugin-web-storage';
import {DashHeader} from '../../../packages/xai-web-dashboard-grid/src/DashHeader';
import {prefMutationLockName} from '../../../packages/plugin-web-storage/src/internal/prefMutation';
import {accountLifecycleLockName} from '../../../packages/plugin-web-storage/src/internal/accountCoordination';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
const key='xai_pref_dashboard_header_note_x';
const nativeSet=Storage.prototype.setItem,nativeGet=Storage.prototype.getItem;
function activate(owner:string){localStorage.setItem(generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'test',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');}
beforeEach(()=>{localStorage.clear();activate('device-A');localStorage.setItem(key,'0');localStorage.setItem(accountScope.physicalKey('xai_pref_dashboard_header_note'),'Current note');vi.stubGlobal('navigator',{locks:createTestLockManager()});});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();});
function mount(){const ui=render(<DashHeader lang="en" now={new Date('2026-09-09T10:00:00Z')}/>);const lane=ui.container.querySelector('.dash-note-lane')!,note=ui.container.querySelector('.dash-note')! as HTMLElement;Object.defineProperty(lane,'clientWidth',{value:760,configurable:true});Object.defineProperty(note,'offsetWidth',{value:360,configurable:true});return {...ui,lane,note,position:()=>note.style.getPropertyValue('--dash-note-x')};}
function begin(note:HTMLElement){fireEvent.pointerDown(note,{button:0,clientX:200,pointerId:1});}
function move(note:HTMLElement,delta:number){fireEvent.pointerMove(note,{clientX:200+delta,pointerId:1});}
function finish(note:HTMLElement,delta:number,cancel=false){fireEvent[cancel?'pointerCancel':'pointerUp'](note,{clientX:200+delta,pointerId:1});}
function drag(note:HTMLElement,delta:number){begin(note);move(note,delta);finish(note,delta);}
async function flush(){await act(async()=>{await new Promise(r=>setTimeout(r,0));});}
function unload(){const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;}
async function hold(name=prefMutationLockName(key)){let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);const task=navigator.locks.request(name,{mode:'exclusive'},()=>{entered();return gate;});await ready;return async()=>{await act(async()=>{release();await task;});await flush();};}
function external(raw:string){const oldValue=localStorage.getItem(key);nativeSet.call(localStorage,key,raw);window.dispatchEvent(new StorageEvent('storage',{key,oldValue,newValue:raw,storageArea:localStorage}));}
function uncertain(){let armed=false,writes=0;const write=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){nativeSet.call(this,k,v);if(k===key){armed=true;writes++;}});const read=vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,k){if(k===key&&armed){armed=false;throw Error('readback unavailable');}return nativeGet.call(this,k);});return {writes:()=>writes,restore:()=>{write.mockRestore();read.mockRestore();}};}
it('gesture movement is local and dirty until pointerup commits exactly its final position',async()=>{const ui=mount();const spy=vi.spyOn(Storage.prototype,'setItem');begin(ui.note);move(ui.note,20);move(ui.note,40);expect.soft(ui.position()).toBe('40px');expect.soft(localStorage.getItem(key)).toBe('0');expect.soft(unload()).toBe(true);finish(ui.note,40);await waitFor(()=>expect(localStorage.getItem(key)).toBe('40'));await flush();expect(spy.mock.calls.filter(c=>c[0]===key)).toEqual([[key,'40']]);fireEvent.click(ui.getByRole('button',{name:'Edit dashboard note'}));expect(ui.queryByRole('textbox')).toBeNull();expect(unload()).toBe(false);});
it('pointercancel terminates a moved gesture with its final position; a plain click never writes',async()=>{const ui=mount();const spy=vi.spyOn(Storage.prototype,'setItem');begin(ui.note);finish(ui.note,0);await flush();expect(spy.mock.calls.filter(c=>c[0]===key)).toEqual([]);begin(ui.note);move(ui.note,35);expect.soft(localStorage.getItem(key)).toBe('0');finish(ui.note,35,true);await waitFor(()=>expect(localStorage.getItem(key)).toBe('35'));expect(spy.mock.calls.filter(c=>c[0]===key)).toEqual([[key,'35']]);});
it('resize clamps only presentation and later expansion restores desired saved coordinate without writes',async()=>{localStorage.setItem(key,'300');const ui=mount();const spy=vi.spyOn(Storage.prototype,'setItem');Object.defineProperty(ui.lane,'clientWidth',{value:560,configurable:true});fireEvent(window,new Event('resize'));await flush();expect.soft(ui.position()).toBe('100px');expect.soft(localStorage.getItem(key)).toBe('300');Object.defineProperty(ui.lane,'clientWidth',{value:1000,configurable:true});fireEvent(window,new Event('resize'));await flush();expect.soft(ui.position()).toBe('300px');expect(spy.mock.calls.filter(c=>c[0]===key)).toEqual([]);});
it('clean storage event adopts device coordinate while a gesture retains frozen raw and latest local position',async()=>{const ui=mount();act(()=>external('60'));await waitFor(()=>expect(ui.position()).toBe('60px'));begin(ui.note);move(ui.note,20);act(()=>external('125'));expect(ui.position()).toBe('80px');finish(ui.note,20);await flush();expect(localStorage.getItem(key)).toBe('125');expect(ui.position()).toBe('80px');expect(unload()).toBe(true);});
it('raw replacement during gesture is preserved even without a storage event',async()=>{const ui=mount();begin(ui.note);move(ui.note,40);nativeSet.call(localStorage,key,'75');finish(ui.note,40);await flush();expect(localStorage.getItem(key)).toBe('75');expect(ui.position()).toBe('40px');expect(unload()).toBe(true);});
it('external replacement while final position waits for key lock refuses without losing draft',async()=>{const ui=mount();const release=await hold();try{drag(ui.note,40);act(()=>external('75'));}finally{await release();}expect(localStorage.getItem(key)).toBe('75');expect(ui.position()).toBe('40px');expect(unload()).toBe(true);});
it('two gestures while first save waits preserve final latest intent and correct predecessor baseline',async()=>{const ui=mount();const release=await hold();try{drag(ui.note,40);drag(ui.note,30);expect.soft(ui.position()).toBe('70px');expect.soft(localStorage.getItem(key)).toBe('0');expect(unload()).toBe(true);}finally{await release();}await waitFor(()=>expect(localStorage.getItem(key)).toBe('70'));expect(ui.position()).toBe('70px');expect(unload()).toBe(false);});
it('quota preserves latest second gesture, exports its position and retries through actual save',async()=>{const ui=mount();const fault=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key)throw Error('quota');nativeSet.call(this,k,v);});drag(ui.note,40);await flush();drag(ui.note,50);await flush();expect(ui.position()).toBe('90px');expect(localStorage.getItem(key)).toBe('0');expect(unload()).toBe(true);let captured:Blob|undefined;vi.stubGlobal('URL',class extends URL{static createObjectURL(b:Blob){captured=b;return 'blob:position';}static revokeObjectURL(){}});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});fireEvent.click(ui.getByText('Export note draft'));expect(captured).toBeDefined();const json=JSON.parse(await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsText(captured!);}));expect(json).toEqual({version:1,kind:'dashboard-note-draft',note:'Current note',noteOffset:90});fault.mockRestore();fireEvent.click(ui.getByText('Retry note save'));await waitFor(()=>expect(localStorage.getItem(key)).toBe('90'));await flush();expect(unload()).toBe(false);});
it('unchanged uncertainty retry reconciles one physical write and clears only verified position recovery',async()=>{const ui=mount();const injection=uncertain();drag(ui.note,40);await flush();expect(nativeGet.call(localStorage,key)).toBe('40');expect(unload()).toBe(true);fireEvent.click(ui.getByText('Retry note save'));await flush();expect(nativeGet.call(localStorage,key)).toBe('40');expect(ui.position()).toBe('40px');expect(injection.writes()).toBe(1);expect(unload()).toBe(false);injection.restore();});
it('uncertain retry does not overwrite a subsequent external position',async()=>{const ui=mount();const injection=uncertain();drag(ui.note,40);await flush();injection.restore();act(()=>external('95'));fireEvent.click(ui.getByText('Retry note save'));await flush();expect(localStorage.getItem(key)).toBe('95');expect(ui.position()).toBe('40px');expect(unload()).toBe(true);});
it('pending device final position survives A to B to locked account without an account admission lock',async()=>{const ui=mount();const release=await hold();try{drag(ui.note,40);act(()=>activate('device-B'));act(()=>accountScope.lock('signed-out'));expect.soft(ui.position()).toBe('40px');}finally{await release();}expect(localStorage.getItem(key)).toBe('40');expect(ui.position()).toBe('40px');expect(unload()).toBe(false);});
it('holding an account lifecycle lock does not prevent an explicit device gesture commit',async()=>{const ui=mount();const release=await hold(accountLifecycleLockName('device-A'));try{drag(ui.note,40);await waitFor(()=>expect(localStorage.getItem(key)).toBe('40'));expect(ui.position()).toBe('40px');}finally{await release();}});
it('earlier commit cannot erase a newer still-open gesture or strand its successful predecessor baseline',async()=>{const ui=mount();const release=await hold();try{drag(ui.note,40);begin(ui.note);move(ui.note,30);expect(ui.position()).toBe('70px');}finally{await release();}expect(localStorage.getItem(key)).toBe('40');expect.soft(ui.position()).toBe('70px');fireEvent(window,new Event('resize'));expect.soft(ui.position()).toBe('70px');finish(ui.note,30);await flush();expect(localStorage.getItem(key)).toBe('70');expect(ui.position()).toBe('70px');expect(unload()).toBe(false);});
