import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {act,cleanup,fireEvent,render,waitFor} from '@testing-library/react';
import {accountScope,generationMarkerKey} from '@repo/plugin-web-storage';
import {DashHeader} from '../../../packages/xai-web-dashboard-grid/src/DashHeader';
import {accountLifecycleLockName} from '../../../packages/plugin-web-storage/src/internal/accountCoordination';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
let key:string;
const set=Storage.prototype.setItem;
function activate(owner:string){accountScope.activate(accountScope.lock(owner),'g1');localStorage.setItem(generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'test',previous:null}));return accountScope.physicalKey('xai_pref_dashboard_header_note');}
beforeEach(()=>{localStorage.clear();key=activate('note-A');localStorage.setItem(key,'Original A');localStorage.setItem('xai_pref_dashboard_header_note_x','0');vi.stubGlobal('navigator',{locks:createTestLockManager()});});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.restoreAllMocks();});
function mount(){const ui=render(<DashHeader lang="en" now={new Date('2026-09-09T10:00:00Z')}/>);return {...ui,edit:()=>fireEvent.click(ui.getByRole('button',{name:'Edit dashboard note'})),input:()=>ui.getByRole('textbox') as HTMLInputElement,save:()=>fireEvent.click(ui.getByRole('button',{name:'Save dashboard note'}))};}
function unload(){const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;}
async function hold(){let release!:()=>void,entered!:()=>void;const ready=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);const held=navigator.locks.request(accountLifecycleLockName('note-A'),{mode:'exclusive'},()=>{entered();return gate;});await ready;return async()=>{await act(async()=>{release();await held;});};}
function external(raw:string){const oldValue=localStorage.getItem(key);set.call(localStorage,key,raw);window.dispatchEvent(new StorageEvent('storage',{key,oldValue,newValue:raw,storageArea:localStorage}));}
function exports(){let blob:Blob|undefined;vi.stubGlobal('URL',class extends URL {static createObjectURL=vi.fn((b:Blob)=>{blob=b;return 'blob:note';});static revokeObjectURL=vi.fn();});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});return async()=>{expect(blob).toBeDefined();return JSON.parse(await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result as string);r.onerror=reject;r.readAsText(blob!);}));};}
it('duplicate Save Enter blur shares one pending commit and preserves unload warning',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Same'}});const release=await hold();const spy=vi.spyOn(Storage.prototype,'setItem');try{ui.save();fireEvent.keyDown(ui.input(),{key:'Enter'});fireEvent.blur(ui.input());expect(unload()).toBe(true);expect(localStorage.getItem(key)).toBe('Original A');}finally{await release();}await waitFor(()=>expect(ui.queryByRole('textbox')).toBeNull());expect(spy.mock.calls.filter(c=>c[0]===key)).toEqual([[key,'Same']]);expect(unload()).toBe(false);});
it('newer explicit submission while first is queued eventually saves latest and closes only latest',async()=>{const ui=mount();ui.edit();const release=await hold();try{fireEvent.change(ui.input(),{target:{value:'First'}});ui.save();fireEvent.change(ui.input(),{target:{value:'Second'}});fireEvent.keyDown(ui.input(),{key:'Enter'});expect(ui.input().value).toBe('Second');}finally{await release();}await waitFor(()=>{expect(localStorage.getItem(key)).toBe('Second');expect(ui.queryByRole('textbox')).toBeNull();});});
it('Clear pending then newer typing keeps editor and warning; next explicit save persists latest',async()=>{const ui=mount();const release=await hold();try{fireEvent.click(ui.getByRole('button',{name:'Clear dashboard note'}));expect(ui.input().value).toBe('');fireEvent.change(ui.input(),{target:{value:'After Clear'}});}finally{await release();}await waitFor(()=>expect(localStorage.getItem(key)).toBe(''));expect(ui.input().value).toBe('After Clear');expect(unload()).toBe(true);ui.save();await waitFor(()=>expect(ui.queryByRole('textbox')).toBeNull());expect(localStorage.getItem(key)).toBe('After Clear');});
it('dirty storage event cannot rebase draft and conflict export contains latest text',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Local latest'}});act(()=>external('External'));ui.save();expect(localStorage.getItem(key)).toBe('External');expect(ui.input().value).toBe('Local latest');const read=exports();fireEvent.click(ui.getByText('Export note draft'));expect(await read()).toEqual({version:1,kind:'dashboard-note-draft',note:'Local latest',noteOffset:0});expect(unload()).toBe(true);});
it('external change while lock queued refuses without replacing draft',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Local queued'}});const release=await hold();try{ui.save();act(()=>external('External queued'));}finally{await release();}await waitFor(()=>expect(ui.getByText(/account or saved content changed/)).toBeTruthy());expect(ui.input().value).toBe('Local queued');expect(localStorage.getItem(key)).toBe('External queued');});
it('A to B pending masks every A note text while retaining inert recovery and refusing old export',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Secret A draft'}});const release=await hold();let b='';try{ui.save();act(()=>{b=activate('note-B');localStorage.setItem(b,'B note');});expect.soft(ui.container.textContent).not.toContain('Original A');expect.soft(ui.queryByDisplayValue('Secret A draft')).toBeNull();expect(unload()).toBe(true);fireEvent.click(ui.getByText('Retry note save'));const spy=exports();fireEvent.click(ui.getByText('Export note draft'));expect(ui.getByText('Export failed. Please retry.')).toBeTruthy();expect(URL.createObjectURL).not.toHaveBeenCalled();}finally{await release();}expect(localStorage.getItem(key)).toBe('Original A');expect(localStorage.getItem(b)).toBe('B note');});
it('clean A to B displays B note and permits independent B editor',async()=>{const ui=mount();let b='';act(()=>{b=activate('note-B');localStorage.setItem(b,'B clean');});await waitFor(()=>expect(ui.getByText('B clean')).toBeTruthy());ui.edit();fireEvent.change(ui.input(),{target:{value:'B edited'}});ui.save();await waitFor(()=>expect(localStorage.getItem(b)).toBe('B edited'));expect(localStorage.getItem(key)).toBe('Original A');});
it('position-only failure can export latest offset and committed note without ever opening note editor',async()=>{const ui=mount();const note=ui.container.querySelector('.dash-note')!,lane=ui.container.querySelector('.dash-note-lane')!;Object.defineProperty(lane,'clientWidth',{value:760});Object.defineProperty(note,'offsetWidth',{value:360});vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k==='xai_pref_dashboard_header_note_x')throw Error('quota');set.call(this,k,v);});fireEvent.pointerDown(note,{button:0,clientX:200,pointerId:1});fireEvent.pointerMove(note,{clientX:290,pointerId:1});fireEvent.pointerUp(note,{clientX:290,pointerId:1});await waitFor(()=>expect(ui.getByRole('alert')).toBeTruthy());const read=exports();fireEvent.click(ui.getByText('Export note draft'));expect(await read()).toEqual({version:1,kind:'dashboard-note-draft',note:'Original A',noteOffset:90});});
it('export failure retains newest draft and unload guard',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Export me'}});act(()=>external('New external'));ui.save();vi.stubGlobal('URL',class extends URL {static createObjectURL(){throw Error('download setup');}});fireEvent.click(ui.getByText('Export note draft'));expect(ui.getByText('Export failed. Please retry.')).toBeTruthy();expect(ui.input().value).toBe('Export me');expect(unload()).toBe(true);expect(localStorage.getItem(key)).toBe('New external');});
it('Escape cancels an unsubmitted edit and reopening captures fresh external baseline',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'Discard'}});fireEvent.keyDown(ui.input(),{key:'Escape'});expect(ui.queryByRole('textbox')).toBeNull();expect(localStorage.getItem(key)).toBe('Original A');act(()=>external('New source'));await waitFor(()=>expect(ui.getByText('New source')).toBeTruthy());ui.edit();fireEvent.change(ui.input(),{target:{value:'New edit'}});ui.save();await waitFor(()=>expect(localStorage.getItem(key)).toBe('New edit'));});
it('changed draft Retry after quota still applies explicit note normalization',async()=>{const ui=mount();ui.edit();fireEvent.change(ui.input(),{target:{value:'First'}});const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key)throw Error('quota');set.call(this,k,v);});ui.save();await waitFor(()=>expect(ui.getByRole('alert')).toBeTruthy());await act(async()=>{await Promise.resolve();});fireEvent.change(ui.input(),{target:{value:'  Latest    text  '}});spy.mockRestore();fireEvent.click(ui.getByText('Retry note save'));await waitFor(()=>expect(ui.queryByRole('textbox')).toBeNull());expect(localStorage.getItem(key)).toBe('Latest text');});
