import React from 'react';
import {it,expect,vi,beforeEach} from 'vitest';
import {act,fireEvent,render,within} from '@testing-library/react';
import {transferableAbortController} from 'node:util';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider,Shell} from '@repo/xai-web-shell';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {fixture,flush,key,nativeSet,nativeGet,hold,activate} from '../web-d2-pomo-device-astra/fixture';
fixture();beforeEach(()=>{vi.stubGlobal('AbortController',transferableAbortController().constructor)});
const path='/app/pomodoro',next='/app/dashboard';
async function host(){const registration=webShellModuleRegistrations.find(r=>r.moduleId==='pomodoro')!;const Module=registration.children.find(r=>r.path==='')!.render;const router=createMemoryRouter([{path:'/app',element:<Shell lang="en" setLang={()=>{}} theme="light" setTheme={()=>{}} density="comfortable" setDensity={()=>{}}/>,children:[{path:'pomodoro',element:<Module/>},{path:'dashboard',element:<div>Dashboard destination</div>},{path:'calendar',element:<div>Calendar destination</div>}]}],{initialEntries:[next,path],initialIndex:1});const originalNavigate=router.navigate;const ui=render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);await flush();return {ui,router,originalNavigate};}
const unload=()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented};
const chooseTheme=(ui:any,v='violet')=>fireEvent.click(ui.getByTestId('theme-'+v));
function denyTheme(){return vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key('theme'))throw Error('quota');nativeSet.call(this,k,v)})}
const nav=async(router:any,to:any)=>{await act(async()=>{await router.navigate(to)});await flush()};
const click=(ui:any,name:RegExp)=>fireEvent.click(ui.getByRole('button',{name}));
it('actual Shell AppRail keeps failed preference until explicit Stay or discard',async()=>{const {ui,router}=await host();denyTheme();chooseTheme(ui);await flush();click(ui,/^Dashboard$/);await flush();expect(router.state.location.pathname).toBe(path);expect(ui.getByRole('dialog')).toBeTruthy();click(ui,/^Stay$/);await flush();expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');click(ui,/^Dashboard$/);await flush();click(ui,/Discard local changes and leave/i);await flush();expect(router.state.location.pathname).toBe(next);expect(nativeGet.call(localStorage,key('theme'))).toBe('"coral"');});
it('Back then competing push replays only first POP and retains Forward history',async()=>{const {ui,router}=await host();denyTheme();chooseTheme(ui);await flush();act(()=>{void router.navigate(-1);void router.navigate('/app/calendar')});await flush();click(ui,/Discard local changes and leave/i);await flush();expect(router.state.location.pathname).toBe(next);await nav(router,1);expect(router.state.location.pathname).toBe(path);expect(ui.getByTestId('theme-coral').getAttribute('aria-pressed')).toBe('true');});
it('signout-first request blocks competing route and Stay resolves false',async()=>{const {ui,router}=await host();denyTheme();chooseTheme(ui);await flush();let p!:Promise<boolean>;await act(async()=>{p=requestSettingsDeparture('sign-out')});await nav(router,next);click(ui,/^Stay$/);await flush();expect(await p).toBe(false);expect(router.state.location.pathname).toBe(path);expect(unload()).toBe(true);});
it('account change cancels old signout decision while device draft remains guarded',async()=>{const {ui,router}=await host();denyTheme();chooseTheme(ui);await flush();let p!:Promise<boolean>;await act(async()=>{p=requestSettingsDeparture('sign-out')});await act(async()=>activate('pomo-departure-B'));await flush();expect(await p).toBe(false);expect(ui.queryByRole('dialog')).toBeNull();expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');expect(unload()).toBe(true);await nav(router,next);expect(ui.getByRole('dialog')).toBeTruthy();});
it('held independent preference siblings release departure only when both latest saves verify',async()=>{const releaseTheme=await hold('theme'),releaseMuted=await hold('muted');const {ui,router}=await host();chooseTheme(ui);fireEvent.click(ui.getByTestId('mute-btn'));await flush();await nav(router,next);await releaseTheme();expect(router.state.location.pathname).toBe(path);expect(unload()).toBe(true);await releaseMuted();expect(router.state.location.pathname).toBe(next);expect(nativeGet.call(localStorage,key('theme'))).toBe('"violet"');expect(nativeGet.call(localStorage,key('muted'))).toBe('true');expect(unload()).toBe(false);});
it('dialog focus is contained and Escape returns control focus without losing draft',async()=>{const {ui,router}=await host();denyTheme();chooseTheme(ui);await flush();const control=ui.getByTestId('theme-violet');control.focus();await nav(router,next);const dialog=ui.getByRole('dialog');expect(dialog.contains(document.activeElement)).toBe(true);const buttons=within(dialog).getAllByRole('button');buttons.at(-1)!.focus();fireEvent.keyDown(buttons.at(-1)!,{key:'Tab'});expect(document.activeElement).toBe(buttons[0]);fireEvent.keyDown(dialog,{key:'Escape'});await flush();expect(ui.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(control);expect(unload()).toBe(true);});
it('unmount cancels pending signout and restores original router method and delegate',async()=>{const {ui,router,originalNavigate}=await host();denyTheme();chooseTheme(ui);await flush();let p!:Promise<boolean>;await act(async()=>{p=requestSettingsDeparture('sign-out')});ui.unmount();expect(await p).toBe(false);expect(router.navigate).toBe(originalNavigate);expect(await requestSettingsDeparture('sign-out')).toBe(true);expect(unload()).toBe(false);});
it('invalid source alone remains repairable without fabricated departure draft',async()=>{nativeSet.call(localStorage,key('sound'),'null');const {ui,router}=await host();expect(ui.getByRole('button',{name:/Reload preferences/i})).toBeTruthy();expect(unload()).toBe(false);await nav(router,next);expect(router.state.location.pathname).toBe(next);});
