import React from './packages/plugin-web-pomodoro/node_modules/react/index.js';import {createRoot} from './packages/plugin-web-pomodoro/node_modules/react-dom/client.js';
import {PomodoroModule} from './packages/plugin-web-pomodoro/src/PomodoroModule.tsx';import {PomodoroSessionHost} from './packages/plugin-web-pomodoro/src/session-host.tsx';import {StatisticsModule} from './packages/plugin-web-statistics/src/StatisticsModule.tsx';
import {command} from './packages/plugin-web-pomodoro/src/internal/sessionController.ts';import {accountScope} from './packages/plugin-web-storage/src/index.ts';
import {aggregateRange} from './packages/plugin-web-statistics/src/internal/aggregators.ts';import {heatmapCells} from './packages/plugin-web-statistics/src/internal/heatmapCells.ts';import {EMPTY_HABITS_STATE} from './packages/plugin-web-statistics/src/internal/isHabitsStateRecord.ts';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-tokens/src/layout.css';import './packages/plugin-web-pomodoro/src/styles.css';import './packages/plugin-web-statistics/src/styles.css';
const NativeDate=Date;let clock=NativeDate.parse('2026-09-09T10:00:00');(globalThis as any).Date=class extends NativeDate{constructor(...args:any[]){super(...(args.length?args:[clock]) as [any])}static now(){return clock}};
accountScope.activate(accountScope.lock('stat-independent'),'g1');const key=accountScope.physicalKey('xai_pomodoro_sessions');const root=createRoot(document.getElementById('app')!);
function route(kind='pomo',lang='en'){sessionStorage.setItem('route',kind);root.render(React.createElement(React.Fragment,null,React.createElement(PomodoroSessionHost),kind==='pomo'?React.createElement(PomodoroModule,{lang}):React.createElement(StatisticsModule,{lang})))}
(window as any).probe={command,route,tick:(ms:number)=>{clock+=ms},raw:()=>localStorage.getItem(key),rows:()=>JSON.parse(localStorage.getItem(key)??'[]'),fixture:()=>{const base={mode:'focus',durationMs:1500000,finishedAt:new Date(clock).toISOString(),completed:false};const rows=[{...base,id:'measured',elapsedMs:60000},{...base,id:'zero',elapsedMs:0},{...base,id:'short1',elapsedMs:15000},{...base,id:'short2',elapsedMs:15000},...([undefined,-1,1500001,'bad',null].map((elapsedMs,i)=>({...base,id:'unknown'+i,elapsedMs}))),{...base,id:'outside',finishedAt:'2025-01-01T12:00:00Z'}];localStorage.setItem(key,JSON.stringify(rows));window.dispatchEvent(new StorageEvent('storage',{key,newValue:localStorage.getItem(key),storageArea:localStorage}));return rows},aggregate:(range='week')=>aggregateRange(range,JSON.parse(localStorage.getItem(key)??'[]'),EMPTY_HABITS_STATE,0,new Date(clock),'en'),heat:()=>heatmapCells(JSON.parse(localStorage.getItem(key)??'[]'),0,new Date(clock))};route(sessionStorage.getItem('route')??'pomo');
