import React from 'react';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';
import {act,cleanup,fireEvent,render} from '@testing-library/react';
import {transferableAbortController} from 'node:util';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider,Shell} from '@repo/xai-web-shell';
import {accountScope,generationMarkerKey} from '@repo/plugin-web-storage';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
const nativeSet=Storage.prototype.setItem,nativeGet=Storage.prototype.getItem;
let noteKey:string;
const path='/app/dashboard',next='/app/tasks';
async function flush(){await act(async()=>{for(let i=0;i<12;i++)await new Promise(r=>setTimeout(r,0));});}
beforeEach(()=>{localStorage.clear();const owner='header-departure-A';nativeSet.call(localStorage,generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');noteKey=accountScope.physicalKey('xai_pref_dashboard_header_note');nativeSet.call(localStorage,noteKey,'Original note');nativeSet.call(localStorage,'xai_pref_dashboard_header_note_x','0');nativeSet.call(localStorage,accountScope.physicalKey('xai_dash_order'),'[]');vi.stubGlobal('AbortController',transferableAbortController().constructor);vi.stubGlobal('navigator',{locks:createTestLockManager()});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>setTimeout(()=>cb(performance.now()),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function host(initialEntries=[path]){const registration=webShellModuleRegistrations.find(r=>r.moduleId==='dashboard')!;const Module=registration.children.find(r=>r.path==='')!.render;const router=createMemoryRouter([{path:'/app',element:<Shell lang="en" setLang={()=>{}} theme="light" setTheme={()=>{}} density="comfortable" setDensity={()=>{}}/>,children:[{path:'dashboard',element:<Module/>},{path:'tasks',element:<div>Tasks destination</div>}]}],{initialEntries});const ui=render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);await flush();return {ui,router};}
async function edit(ui:ReturnType<typeof render>,save:boolean){fireEvent.click(ui.getByRole('button',{name:'Edit dashboard note'}));const input=ui.container.querySelector('.dash-note input')!;fireEvent.change(input,{target:{value:'Latest unsaved note'}});if(save){vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===noteKey)throw Error('quota');nativeSet.call(this,k,v)});fireEvent.click(ui.getByRole('button',{name:'Save dashboard note'}));}await flush();expect(nativeGet.call(localStorage,noteKey)).toBe('Original note');expect((ui.container.querySelector('.dash-note input') as HTMLInputElement).value).toBe('Latest unsaved note');}

const unload=()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented};
it('actual Back remains on Header and replays the first POP only after explicit discard',async()=>{const {ui,router}=await host([next,path]);await edit(ui,true);await act(async()=>{await router.navigate(-1)});await flush();expect(router.state.location.pathname).toBe(path);expect(ui.getByRole('dialog')).toBeTruthy();await act(async()=>{await router.navigate('/app/tasks?later=1')});await flush();fireEvent.click(ui.getByRole('button',{name:/discard.*leave/i}));await flush();expect(router.state.location.pathname).toBe(next);expect(router.state.location.search).toBe('');await act(async()=>{await router.navigate(1)});expect(router.state.location.pathname).toBe(path);});
it('first signout holds a competing route until Stay cancels the original intent',async()=>{const {ui,router}=await host();await edit(ui,true);let outcome:unknown='pending';await act(async()=>{void requestSettingsDeparture('sign-out').then(v=>outcome=v);void router.navigate(next)});await flush();expect(outcome).toBe('pending');expect(router.state.location.pathname).toBe(path);fireEvent.click(ui.getByRole('button',{name:/^stay$/i}));await flush();expect(outcome).toBe(false);expect(router.state.location.pathname).toBe(path);expect((ui.container.querySelector('.dash-note input') as HTMLInputElement).value).toBe('Latest unsaved note');});
it('source-only invalid device position retains source recovery but creates no unload or host draft',async()=>{nativeSet.call(localStorage,'xai_pref_dashboard_header_note_x','null');const {ui,router}=await host();expect(ui.getByRole('button',{name:'Reload note position'})).toBeTruthy();expect(unload()).toBe(false);expect(await requestSettingsDeparture('sign-out')).toBe(true);await act(async()=>{await router.navigate(next)});expect(router.state.location.pathname).toBe(next);expect(nativeGet.call(localStorage,'xai_pref_dashboard_header_note_x')).toBe('null');});
it('epoch change cancels pending Header intent without exposing frozen A note',async()=>{const {ui}=await host();await edit(ui,true);let outcome:unknown='pending';await act(async()=>{void requestSettingsDeparture('sign-out').then(v=>outcome=v)});await flush();expect(outcome).toBe('pending');await act(async()=>{const owner='header-departure-B';nativeSet.call(localStorage,generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture-B',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');});await flush();expect(outcome).toBe(false);expect(ui.queryByRole('dialog')).toBeNull();expect(ui.container.textContent).not.toContain('Latest unsaved note');expect(ui.container.textContent).not.toContain('Original note');expect(unload()).toBe(true);expect(await requestSettingsDeparture('sign-out')).toBe(true);});
it('unmount cancels pending Header signout and restores actual router method',async()=>{const {ui,router}=await host();await edit(ui,true);let outcome:unknown='pending';await act(async()=>{void requestSettingsDeparture('sign-out').then(v=>outcome=v)});await flush();expect(outcome).toBe('pending');ui.unmount();await flush();expect(outcome).toBe(false);expect(await requestSettingsDeparture('sign-out')).toBe(true);await router.navigate(next);expect(router.state.location.pathname).toBe(next);});
