import React from 'react';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';
import {act,cleanup,fireEvent,render} from '@testing-library/react';
import {transferableAbortController} from 'node:util';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider,Shell} from '@repo/xai-web-shell';
import {accountScope,generationMarkerKey} from '@repo/plugin-web-storage';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
const nativeSet=Storage.prototype.setItem,nativeGet=Storage.prototype.getItem;
let noteKey:string;
const path='/app/dashboard',next='/app/tasks';
async function flush(){await act(async()=>{for(let i=0;i<12;i++)await new Promise(r=>setTimeout(r,0));});}
beforeEach(()=>{localStorage.clear();const owner='header-departure-A';nativeSet.call(localStorage,generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');noteKey=accountScope.physicalKey('xai_pref_dashboard_header_note');nativeSet.call(localStorage,noteKey,'Original note');nativeSet.call(localStorage,'xai_pref_dashboard_header_note_x','0');nativeSet.call(localStorage,accountScope.physicalKey('xai_dash_order'),'[]');vi.stubGlobal('AbortController',transferableAbortController().constructor);vi.stubGlobal('navigator',{locks:createTestLockManager()});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>setTimeout(()=>cb(performance.now()),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function host(){const registration=webShellModuleRegistrations.find(r=>r.moduleId==='dashboard')!;const Module=registration.children.find(r=>r.path==='')!.render;const router=createMemoryRouter([{path:'/app',element:<Shell lang="en" setLang={()=>{}} theme="light" setTheme={()=>{}} density="comfortable" setDensity={()=>{}}/>,children:[{path:'dashboard',element:<Module/>},{path:'tasks',element:<div>Tasks destination</div>}]}],{initialEntries:[path]});const ui=render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);await flush();return {ui,router};}
async function edit(ui:ReturnType<typeof render>,save:boolean){fireEvent.click(ui.getByRole('button',{name:'Edit dashboard note'}));const input=ui.container.querySelector('.dash-note input')!;fireEvent.change(input,{target:{value:'Latest unsaved note'}});if(save){vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===noteKey)throw Error('quota');nativeSet.call(this,k,v)});fireEvent.click(ui.getByRole('button',{name:'Save dashboard note'}));}await flush();expect(nativeGet.call(localStorage,noteKey)).toBe('Original note');expect((ui.container.querySelector('.dash-note input') as HTMLInputElement).value).toBe('Latest unsaved note');}
it('actual Dashboard registration keeps a quota-failed note behind route decision',async()=>{const {ui,router}=await host();await edit(ui,true);await act(async()=>{await router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(path);expect(ui.getByRole('dialog')).toBeTruthy();});
it('unsubmitted actual Header text is protected before programmatic departure',async()=>{const {ui,router}=await host();await edit(ui,false);await act(async()=>{await router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(path);expect(ui.getByRole('dialog')).toBeTruthy();});
it('actual Shell AppRail preserves failed Header note',async()=>{const {ui,router}=await host();await edit(ui,true);const rail=ui.container.querySelector('.app-rail [aria-label="Tasks"]')!;expect(rail).not.toBeNull();fireEvent.click(rail);await flush();expect(router.state.location.pathname).toBe(path);expect(ui.getByRole('dialog')).toBeTruthy();});
it('actual App signout preflight remains pending for current Header draft',async()=>{const {ui}=await host();await edit(ui,true);let outcome:unknown='pending';await act(async()=>{void requestSettingsDeparture('sign-out').then(value=>outcome=value)});await flush();expect(outcome).toBe('pending');expect(ui.getByRole('dialog')).toBeTruthy();});
it('clean Header does not block current signout or normal navigation',async()=>{const {router}=await host();expect(await requestSettingsDeparture('sign-out')).toBe(true);await act(async()=>{await router.navigate(next)});expect(router.state.location.pathname).toBe(next);});
