import React from 'react';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';
import {act,cleanup,fireEvent,render,within} from '@testing-library/react';
import {transferableAbortController} from 'node:util';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider,Shell} from '@repo/xai-web-shell';
import {accountScope,generationMarkerKey,prefMutationLockName} from '@repo/plugin-web-storage';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {composedSettingsRegistration} from '../../../apps/web/src/routes/modules/composedSettingsRegistration';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
const nativeSet=Storage.prototype.setItem,nativeGet=Storage.prototype.getItem;
const keys=['xai_pref_notif_enabled','xai_pref_notif_done_sound','xai_pref_notif_push_task','xai_pref_notif_push_pomo','xai_pref_notif_push_habit','xai_pref_notif_quiet','xai_pref_notif_quiet_start','xai_pref_notif_quiet_end'];
const defaults=['true','subtle','true','true','false','true','22:00','07:00'];
const pane='/app/settings/notifications',next='/app/settings/date_time';
async function flush(rounds=10){await act(async()=>{for(let i=0;i<rounds;i++)await new Promise(r=>setTimeout(r,0));});}
function owner(name:string){nativeSet.call(localStorage,generationMarkerKey(name),JSON.stringify({generation:'g1',migrationId:'notif-host-astra',previous:null}));accountScope.activate(accountScope.lock(name),'g1');}
beforeEach(()=>{localStorage.clear();owner('notif-host-astra-A');keys.forEach((key,i)=>nativeSet.call(localStorage,key,defaults[i]));vi.stubGlobal('AbortController',transferableAbortController().constructor);vi.stubGlobal('navigator',{locks:createTestLockManager()});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>setTimeout(()=>cb(performance.now()),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function host(initialEntries=[pane],initialIndex=initialEntries.length-1){const Composed=composedSettingsRegistration.children[0]!.render;const router=createMemoryRouter([{path:'/app',element:<Shell lang="en" setLang={()=>{}} theme="light" setTheme={()=>{}} density="comfortable" setDensity={()=>{}}/>,children:[{path:'settings/*',element:<Composed/>},{path:'dashboard',element:<div>Dashboard destination</div>},{path:'tasks',element:<div>Tasks destination</div>}]}],{initialEntries,initialIndex});const ui=render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);await flush();const element=ui.container.querySelector('.notif-pane')!;expect(element).toBeTruthy();const q=within(element as HTMLElement);expect((q.getByRole('combobox') as HTMLSelectElement).value).toBe('subtle');expect(q.getAllByRole('switch').map(e=>e.getAttribute('aria-checked'))).toEqual(['true','true','true','false','true']);if(nativeGet.call(localStorage,keys[6])==='22:00')expect((q.getByLabelText('Quiet hours start') as HTMLInputElement).value).toBe('22:00');return{ui,q,router};}
const dialog=(ui:ReturnType<typeof render>)=>within(ui.getByRole('dialog'));
const quiet=(q:ReturnType<typeof within>)=>fireEvent.click(q.getByRole('switch',{name:'Enable quiet hours'}));
const time=(q:ReturnType<typeof within>,value='23:15',field='start')=>fireEvent.change(q.getByLabelText(`Quiet hours ${field}`),{target:{value}});
function deny(indices:number[]){vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(indices.some(i=>k===keys[i]))throw Error('quota');nativeSet.call(this,k,v);});}
async function failed(){const h=await host();deny([6]);time(h.q);await flush();quiet(h.q);await flush();expect(h.q.queryByLabelText('Quiet hours start')).toBeNull();return h;}
async function hold(index:number){let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);const done=navigator.locks.request(prefMutationLockName(keys[index]),{mode:'exclusive'},()=>{entered();return gate});await ready;return async()=>{await act(async()=>{release();await done;});await flush();};}
const warn=()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;};
it.each(['sidebar','rail'])('actual %s producer holds hidden time and discard leaves without writes',async producer=>{const {ui,router}=await failed();const writes=vi.spyOn(Storage.prototype,'setItem'),removes=vi.spyOn(Storage.prototype,'removeItem');if(producer==='sidebar')fireEvent.click(within(ui.container.querySelector('.settings-sidebar') as HTMLElement).getByRole('button',{name:'Date & Time'}));else fireEvent.click(ui.container.querySelector('.app-rail [aria-label="Tasks"]')!);await flush();expect(router.state.location.pathname).toBe(pane);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(producer==='sidebar'?next:'/app/tasks');expect(nativeGet.call(localStorage,keys[6])).toBe('22:00');expect(writes).not.toHaveBeenCalled();expect(removes).not.toHaveBeenCalled();});
it('first route beats same-turn route and signout; Stay preserves hidden work and new intent remains guarded',async()=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{void router.navigate(next);void router.navigate('/app/dashboard');void requestSettingsDeparture('sign-out').then(x=>out=x);});await flush();expect(router.state.location.pathname).toBe(pane);expect(out).toBe(false);fireEvent.click(dialog(ui).getByRole('button',{name:'Stay'}));await flush();expect(ui.queryByRole('dialog')).toBeNull();expect(q.getByRole('button',{name:'Retry Quiet hours start'})).toBeTruthy();act(()=>{void router.navigate(next);void router.navigate('/app/dashboard');});await flush();fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(next);});
it('first signout beats same-turn route; Escape declines without losing hidden recovery',async()=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{void requestSettingsDeparture('sign-out').then(x=>out=x);void router.navigate(next);});await flush();expect(out).toBe('pending');expect(router.state.location.pathname).toBe(pane);fireEvent.keyDown(ui.getByRole('dialog'),{key:'Escape'});await flush();expect(out).toBe(false);expect(router.state.location.pathname).toBe(pane);expect(q.getByRole('button',{name:'Retry Quiet hours start'})).toBeTruthy();expect(warn()).toBe(true);});
it.each([-1,1])('numeric history %s holds URL and location key then replays exact destination',async delta=>{const entries=delta===-1?['/app/dashboard',pane]:[pane,'/app/dashboard'];const {ui,q,router}=await host(entries,delta===-1?1:0);deny([6]);time(q);await flush();quiet(q);await flush();const key=router.state.location.key;act(()=>{void router.navigate(delta)});await flush();expect(router.state.location.pathname).toBe(pane);expect(router.state.location.key).toBe(key);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe('/app/dashboard');});
it('relative Settings navigation preserves destination and options after explicit discard',async()=>{const {ui,router}=await failed();act(()=>{void router.navigate('../date_time',{relative:'path',state:{origin:'notifications'}})});await flush();expect(router.state.location.pathname).toBe(pane);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(next);expect(router.state.location.state).toEqual({origin:'notifications'});});
it('partial hidden Retry cannot release intent; every latest verified clean releases exactly once',async()=>{const {ui,q,router}=await host();let denied=true;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(denied&&(k===keys[0]||k===keys[6]))throw Error('quota');nativeSet.call(this,k,v);});fireEvent.click(q.getByRole('switch',{name:'Enable notifications'}));time(q);await flush();quiet(q);await flush();const destinations:string[]=[];const unsubscribe=router.subscribe(state=>{if(state.location.pathname!==pane)destinations.push(state.location.pathname);});act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(pane);denied=false;fireEvent.click(q.getByRole('button',{name:'Retry Enable notifications'}));await flush();expect(nativeGet.call(localStorage,keys[0])).toBe('false');expect(router.state.location.pathname).toBe(pane);expect(ui.getByRole('dialog')).toBeTruthy();fireEvent.click(q.getByRole('button',{name:'Retry Quiet hours start'}));await flush();expect(nativeGet.call(localStorage,keys[6])).toBe('23:15');expect(router.state.location.pathname).toBe(next);expect(ui.queryByRole('dialog')).toBeNull();expect(destinations).toEqual([next]);unsubscribe();});
it('held hidden save protects navigation and auto releases only after physical verification',async()=>{const {ui,q,router}=await host();const release=await hold(6);try{time(q);quiet(q);await flush();expect(nativeGet.call(localStorage,keys[6])).toBe('22:00');act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(pane);expect(ui.getByRole('dialog')).toBeTruthy();}finally{await release();}expect(nativeGet.call(localStorage,keys[6])).toBe('23:15');expect(router.state.location.pathname).toBe(next);});
it.each(['route','signout'])('epoch cancels old %s while fresh locked hidden work protects new decisions',async producer=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{if(producer==='route')void router.navigate(next);else void requestSettingsDeparture('sign-out').then(x=>out=x)});await flush();expect(ui.getByRole('dialog')).toBeTruthy();act(()=>owner('notif-host-astra-B'));await flush();expect(ui.queryByRole('dialog')).toBeNull();if(producer==='signout')expect(out).toBe(false);expect(router.state.location.pathname).toBe(pane);expect(q.getByRole('button',{name:'Retry Quiet hours start'})).toBeTruthy();act(()=>accountScope.lock('notif-host-astra-locked'));await flush();act(()=>{void router.navigate('/app/dashboard')});await flush();expect(ui.getByRole('dialog')).toBeTruthy();fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe('/app/dashboard');});
it('unmount cancels pending signout and removes hidden-work unload warning',async()=>{const {ui}=await failed();let out:unknown='pending';act(()=>{void requestSettingsDeparture('sign-out').then(x=>out=x)});await flush();expect(out).toBe('pending');expect(warn()).toBe(true);ui.unmount();await flush();expect(out).toBe(false);expect(warn()).toBe(false);});
it('host export remains pending and memory-only; Stay returns all hidden work',async()=>{const {ui,q,router}=await failed();let out:unknown='pending',blob:Blob|null=null;vi.stubGlobal('URL',{createObjectURL:vi.fn((value:Blob)=>{blob=value;return'blob:notif-host';}),revokeObjectURL:vi.fn()});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});act(()=>{void requestSettingsDeparture('sign-out').then(x=>out=x)});await flush();expect(out).toBe('pending');const reads=vi.spyOn(Storage.prototype,'getItem'),writes=vi.spyOn(Storage.prototype,'setItem');fireEvent.click(dialog(ui).getByRole('button',{name:'Export current draft'}));await flush();expect(click).toHaveBeenCalledTimes(1);expect(reads).not.toHaveBeenCalled();expect(writes).not.toHaveBeenCalled();expect(out).toBe('pending');expect(router.state.location.pathname).toBe(pane);const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsText(blob!);});expect(JSON.parse(data)).toEqual({version:1,kind:'notifications-draft',values:{device:{quiet_start:'23:15'}}});fireEvent.click(dialog(ui).getByRole('button',{name:'Stay'}));await flush();expect(out).toBe(false);expect(q.getByRole('button',{name:'Retry Quiet hours start'})).toBeTruthy();expect(warn()).toBe(true);});
it('older successful time cannot release held route when latest queued choice fails',async()=>{const {ui,q,router}=await host();const release=await hold(6);let failLatest=true;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===keys[6]&&v==='00:30'&&failLatest)throw Error('latest quota');nativeSet.call(this,k,v);});try{time(q,'23:15');time(q,'00:30');quiet(q);await flush();act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(pane);}finally{await release();}await flush();expect(nativeGet.call(localStorage,keys[6])).toBe('23:15');expect(router.state.location.pathname).toBe(pane);expect(ui.getByRole('dialog')).toBeTruthy();expect(warn()).toBe(true);failLatest=false;fireEvent.click(q.getByRole('button',{name:'Retry Quiet hours start'}));await flush();expect(nativeGet.call(localStorage,keys[6])).toBe('00:30');expect(router.state.location.pathname).toBe(next);});
it('source-only hidden invalid time stays nonblocking and normal route still works',async()=>{nativeSet.call(localStorage,keys[6],'25:00');const {ui,q,router}=await host();quiet(q);await flush();expect(q.queryByLabelText('Quiet hours start')).toBeNull();expect(warn()).toBe(false);expect(await requestSettingsDeparture('sign-out')).toBe(true);act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(next);expect(ui.queryByRole('dialog')).toBeNull();});
