import React,{useCallback} from './packages/xai-web-tasks/node_modules/react/index.js';
import {createRoot} from './packages/xai-web-tasks/node_modules/react-dom/client.js';
import {WebAuthSessionProvider,useWebAuthSession} from './packages/web-auth-device-session/src/session.tsx';
import {createAuthGenerationStore} from './packages/web-auth-device-session/src/auth-generation-store.ts';
import {accountScope,accountPrefix} from './packages/plugin-web-storage/src/index.ts';
import {AccountDeletionRecoveryNotice} from './packages/plugin-web-settings-rest/src/AccountDeletionRecoveryNotice.tsx';
import {useAccountDeleteOrchestrator} from './packages/plugin-web-settings-rest/src/internal/useAccountDeleteOrchestrator.ts';
import {beginAccountLocalDeletion,resumeAccountLocalDeletion,listPendingAccountDeletions,readAccountDeletionReceipt} from './packages/plugin-web-settings-rest/src/internal/accountDeletionRecovery.ts';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-settings-rest/src/styles.css';
/* HOST_BRIDGE */
const config={url:location.origin,anonKey:'synthetic-public-key',storageKey:'independent-delete-auth',autoRefreshToken:false};
const store=createAuthGenerationStore({storageKey:config.storageKey});let context:any;let fault='';
const originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,...args:any[]){if(fault==='revoke'&&value?.state==='revoked'){this.transaction.abort();throw new DOMException('Injected native transaction abort','AbortError')}return originalPut.call(this,value,...args)};
const originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key:string,value:string){if(fault==='complete'&&key.endsWith(':deleted')&&JSON.parse(value).phase==='complete')throw new DOMException('Injected final receipt quota','QuotaExceededError');return originalSet.call(this,key,value)};
function DeleteButton(){const action=useAccountDeleteOrchestrator();return <><button id="delete" onClick={()=>void action.submit()}>Delete synthetic account</button><output id="delete-state">{action.state}</output></>}
let lastOwner="none";function Child(){context=useWebAuthSession();lastOwner=context.session?.user.id??lastOwner;return <><output id="auth">{context.state}:{context.session?.user.id??''}</output><DeleteButton key={lastOwner}/><AccountDeletionRecoveryBridge/></>}
function identity(owner:string|null){const scope=accountScope.lock(owner);if(owner)accountScope.activate(scope,'business-'+owner)}
function session(owner:string){return {access_token:'synthetic-'+owner,refresh_token:'synthetic-refresh-'+owner,token_type:'bearer',expires_in:86400,expires_at:Math.floor(Date.now()/1000)+86400,user:{id:owner,aud:'authenticated',role:'authenticated',email:owner+'@example.invalid',app_metadata:{},user_metadata:{},created_at:new Date().toISOString()}}}
async function seed(owner:string){const generation='auth-'+owner+'-'+crypto.randomUUID();await store.createCandidate({generation});await store.setSessionItem({generation},'session',JSON.stringify(session(owner)),owner);await store.publish({lease:{generation},owner,expectedActive:(await store.readActive())?.generation??null});return generation}
if(!sessionStorage.getItem('seeded')){await seed('A');sessionStorage.setItem('seeded','1')}
createRoot(document.getElementById('app')!).render(<WebAuthSessionProvider config={config} onIdentityChange={identity}><Child/></WebAuthSessionProvider>);
(window as any).probe={fault:(value:string)=>{fault=value},active:()=>store.readActive(),sessionRaw:async()=>{const a=await store.readActive();return a?store.getItem(a,'session'):null},businessRaw:()=>localStorage.getItem(accountScope.physicalKey('xai_task_cols')),pending:listPendingAccountDeletions,receipt:(owner='A')=>readAccountDeletionReceipt(owner),auth:()=>context.coordinator.capture(),owner:()=>context.session?.user.id,rows:()=>store.readRecovery(),loginB:async()=>{const r=await context.coordinator.signInWithPassword({email:'B@example.invalid',password:'synthetic'});return r},seedBusiness:()=>{localStorage.setItem(accountScope.physicalKey('xai_task_cols'),'[{"tasks":[]}]')},v1:async()=>{const scope={kind:'account',accountId:'legacy',generation:'legacy-business',epoch:-1};const r=beginAccountLocalDeletion(scope as any);let calls=0;await resumeAccountLocalDeletion(r,async()=>{calls++});return {calls,receipt:readAccountDeletionReceipt('legacy')}},missing:async()=>{const r=beginAccountLocalDeletion({kind:'account',accountId:'unavailable',generation:'data-unavailable',epoch:-1},'auth-unavailable');try{await resumeAccountLocalDeletion(r)}catch{}return readAccountDeletionReceipt('unavailable')},clearMissing:()=>localStorage.removeItem(accountPrefix('unavailable',false)+'deleted')};
