export * from "./types";
export { LocalStorageAdapter } from "./data/LocalStorageAdapter";
export { PluginSlotRegistry, createDefaultConsoleNavItems } from "./registry/PluginSlotRegistry";
export type { SearchProvider } from "./registry/PluginSlotRegistry";
export { useCommandPalette } from "./hooks/useCommandPalette";
export type { CommandPaletteController, UseCommandPaletteOptions } from "./hooks/useCommandPalette";
export { NotificationStoreProvider, useNotificationStore } from "./hooks/useNotificationStore";
export type { NotificationStore, NotificationStoreProviderProps } from "./hooks/useNotificationStore";
export { ConsoleDesktopBridge, gridItemToTask } from "./bridge/ConsoleDesktopBridge";
export type { ConsoleDesktopEventHandler } from "./bridge/ConsoleDesktopBridge";
export { ConsoleLayout } from "./components/ConsoleLayout";
export type { ConsoleLayoutProps } from "./components/ConsoleLayout";
export { ConsoleSearch } from "./components/ConsoleSearch";
export type { ConsoleSearchProps } from "./components/ConsoleSearch";
export { ConsoleSettings } from "./components/ConsoleSettings";
export { CommandPalette } from "./components/CommandPalette";
export type { CommandPaletteProps } from "./components/CommandPalette";
export { SearchResult } from "./components/SearchResult";
export type { SearchResultProps } from "./components/SearchResult";
export { NotificationPanel } from "./components/NotificationPanel";
