import React from '../../../packages/xai-web-tasks/node_modules/react';
import {act,cleanup,fireEvent,render,renderHook,screen,within} from '../../../packages/xai-web-tasks/node_modules/@testing-library/react';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {accountScope,generationKey,generationMarkerKey} from '../../../packages/plugin-web-storage/src/index';
import {TasksModule} from '../../../packages/xai-web-tasks/src/TasksModule';
import {BookkeepingModule} from '../../../packages/plugin-web-bookkeeping/src/BookkeepingModule';
import {useBookkeepingState} from '../../../packages/plugin-web-bookkeeping/src/internal/storage';
import {createSeedBookkeepingState} from '../../../packages/plugin-web-bookkeeping/src/internal/defaults';
const key=(logical:string)=>generationKey('joint-A','g1',logical);
const bk=()=>key('xai_bk_state_v2');
beforeEach(()=>{localStorage.clear();const locked=accountScope.lock('joint-A');localStorage.setItem(generationMarkerKey('joint-A'),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(locked,'g1');const seed=createSeedBookkeepingState();seed.budgetTotal=111;localStorage.setItem(bk(),JSON.stringify(seed));localStorage.setItem('xai_bk_view','detail');localStorage.setItem('xai_bk_calendar_mode','month');HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();});
function deny(keys:string[]){const raw=Storage.prototype.setItem;return vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(k,v){if(keys.includes(k))throw new DOMException('Independent quota fault','QuotaExceededError');return raw.call(this,k,v);});}
it('Bookkeeping failed proposal remains unchanged despite subsequent edits; two retries produce one transaction',()=>{
 const {result}=renderHook(()=>useBookkeepingState());const fail=deny([bk()]);const before=result.current[0].tx.length;
 act(()=>result.current[1](s=>({...s,tx:[...s.tx,{...s.tx[0]!,id:'independent-row',note:'preserved proposal'}]})));
 act(()=>result.current[1](s=>({...s,budgetTotal:999})));
 expect(result.current[0].budgetTotal).toBe(111);expect(result.current[2].pending?.value.budgetTotal).toBe(111);expect(JSON.parse(result.current[2].exportDraft()).state.tx.at(-1).note).toBe('preserved proposal');
 fail.mockRestore();const writes=vi.spyOn(Storage.prototype,'setItem');act(()=>{expect(result.current[2].retry()).toBe(true);expect(result.current[2].retry()).toBe(true);});
 expect(JSON.parse(localStorage.getItem(bk())!).tx.length).toBe(before+1);expect(writes.mock.calls.filter(([k])=>k===bk())).toHaveLength(1);
});
it('Bookkeeping two failed mirrors preserve successful mirrors and retries never rewrite business content',()=>{
 const {result}=renderHook(()=>useBookkeepingState());const fail=deny(['xai_bk_view','xai_bk_calendar_mode']);
 act(()=>result.current[1](s=>({...s,budgetTotal:222,prefs:{...s.prefs,billsView:'overview',calendarMode:'year',dashboardOrder:'quick-first'}})));
 const canonical=localStorage.getItem(bk());expect(JSON.parse(canonical!).budgetTotal).toBe(222);expect(result.current[0].budgetTotal).toBe(222);expect(result.current[0].prefs.billsView).toBe('detail');expect(result.current[0].prefs.calendarMode).toBe('month');expect(localStorage.getItem('xai_bk_dash_order')).toBe('quick-first');expect(result.current[2].pending?.canonicalCommitted).toBe(true);
 fail.mockRestore();const writes=vi.spyOn(Storage.prototype,'setItem');act(()=>{result.current[2].retry();result.current[2].retry();});expect(localStorage.getItem(bk())).toBe(canonical);expect(writes.mock.calls.filter(([k])=>k===bk())).toHaveLength(0);expect(localStorage.getItem('xai_bk_view')).toBe('overview');expect(localStorage.getItem('xai_bk_calendar_mode')).toBe('year');
});
it('Bookkeeping rejects stale pending export and retry after B activation without affecting A or B bytes',()=>{
 const {result}=renderHook(()=>useBookkeepingState());const fail=deny([bk()]);act(()=>result.current[1](s=>({...s,budgetTotal:333})));fail.mockRestore();const before=localStorage.getItem(bk()),stale=result.current[2];accountScope.activate(accountScope.lock('joint-B'),'g2');const b=generationKey('joint-B','g2','xai_bk_state_v2');localStorage.setItem(b,'B protected');act(()=>expect(stale.retry()).toBe(false));expect(()=>stale.exportDraft()).toThrow();expect(localStorage.getItem(b)).toBe('B protected');expect(localStorage.getItem(bk())).toBe(before);
});
it.each([['新建账本','账本名称'],['新建账户','账户名称'],['分类与备注','名称']])('Bookkeeping %s keeps the editor until an explicit discard', (button,label)=>{
 const original=localStorage.getItem(bk());render(<BookkeepingModule lang="zh"/>);fireEvent.click(screen.getByRole('button',{name:button}));const input=screen.getByLabelText(label) as HTMLInputElement;fireEvent.change(input,{target:{value:'independent modal draft'}});deny([bk()]);fireEvent.click(screen.getByRole('button',{name:button==='分类与备注'?'保存全部':'保存'}));expect(input.value).toBe('independent modal draft');expect(screen.getByRole('alertdialog').textContent).toContain('草稿');expect(document.querySelector('.bk-workspace')?.hasAttribute('inert')).toBe(true);fireEvent.click(screen.getByRole('button',{name:'放弃未保存更改'}));expect(localStorage.getItem(bk())).toBe(original);expect(document.querySelector('[role=alertdialog]')).toBeNull();
});
it.each([['周期','新建周期','金额','81'],['投资','新增持仓','持有份额','22']])('Bookkeeping %s failed modal retries its original proposal once',(tab,button,label,value)=>{
 render(<BookkeepingModule lang="zh"/>);fireEvent.click(within(document.querySelector('.bk-tabs') as HTMLElement).getByRole('button',{name:tab}));fireEvent.click(screen.getByRole('button',{name:button}));if(tab==='投资')fireEvent.change(screen.getByLabelText('名称'),{target:{value:'independent holding'}});const input=screen.getByLabelText(label) as HTMLInputElement;fireEvent.change(input,{target:{value}});const fail=deny([bk()]);fireEvent.click(screen.getByRole('button',{name:'保存'}));expect(input.value).toBe(value);expect(screen.getByRole('alertdialog')).toBeTruthy();fail.mockRestore();const writes=vi.spyOn(Storage.prototype,'setItem');fireEvent.click(screen.getByRole('button',{name:'重试保存'}));expect(screen.queryByRole('alertdialog')).toBeNull();expect(writes.mock.calls.filter(([k])=>k===bk())).toHaveLength(1);
});
it('Tasks detail retains edited title, notes and date after rejection and commits exactly one matching task',()=>{
 render(<TasksModule lang="en"/>);fireEvent.click(document.querySelector('.task-card')!);const panel=within(document.querySelector('.task-detail-panel') as HTMLElement);fireEvent.change(panel.getByLabelText('Title'),{target:{value:'independent title'}});fireEvent.change(panel.getByLabelText('Notes'),{target:{value:'independent multiline\nnotes'}});fireEvent.change(panel.getByLabelText('Due date'),{target:{value:'2026-10-03'}});const before=localStorage.getItem(key('xai_task_cols'));const fail=deny([key('xai_task_cols')]);fireEvent.click(document.querySelector('.task-detail-panel .task-composer__btn--primary')!);expect(localStorage.getItem(key('xai_task_cols'))).toBe(before);expect((panel.getByLabelText('Notes') as HTMLTextAreaElement).value).toBe('independent multiline\nnotes');expect(panel.getByRole('alert')).toBeTruthy();fail.mockRestore();fireEvent.click(document.querySelector('.task-detail-panel .task-composer__btn--primary')!);const matches=JSON.parse(localStorage.getItem(key('xai_task_cols'))!).flatMap((x:any)=>x.tasks).filter((x:any)=>x.title.en==='independent title');expect(matches).toHaveLength(1);expect(matches[0]).toMatchObject({notes:'independent multiline\nnotes',dueDate:'2026-10-03'});
});
it.each(['list','tag'])('Tasks %s metadata failure remains retryable and creates exactly one item',(kind)=>{
 render(<TasksModule lang="en"/>);fireEvent.click(screen.getByRole('button',{name:'New '+kind}));const dialog=document.querySelector('.task-meta-dialog') as HTMLElement;fireEvent.change(within(dialog).getByLabelText('English label'),{target:{value:'Independent '+kind}});const storageKey=key('xai_pref_task_'+(kind==='list'?'lists':'tags'));const before=localStorage.getItem(storageKey),fail=deny([storageKey]);fireEvent.click(dialog.querySelector('.task-composer__btn--primary')!);expect(localStorage.getItem(storageKey)).toBe(before);expect(within(dialog).getByRole('alert')).toBeTruthy();fail.mockRestore();fireEvent.click(dialog.querySelector('.task-composer__btn--primary')!);expect(JSON.parse(localStorage.getItem(storageKey)!).filter((x:any)=>x.name.en==='Independent '+kind)).toHaveLength(1);
});
it('Tasks retained detail retry and export reject the replaced owner',()=>{
 render(<TasksModule lang="en"/>);fireEvent.click(document.querySelector('.task-card')!);const panel=within(document.querySelector('.task-detail-panel') as HTMLElement);fireEvent.change(panel.getByLabelText('Title'),{target:{value:'A-only private detail'}});const fail=deny([key('xai_task_cols')]);fireEvent.click(document.querySelector('.task-detail-panel .task-composer__btn--primary')!);fail.mockRestore();const before=localStorage.getItem(key('xai_task_cols'));const b=generationKey('joint-B','g2','xai_task_cols');localStorage.setItem(b,'B protected');act(()=>{accountScope.activate(accountScope.lock('joint-B'),'g2')});fireEvent.click(document.querySelector('.task-detail-panel .task-composer__btn--primary')!);const create=vi.fn();vi.stubGlobal('URL',class extends URL{static createObjectURL=create});fireEvent.click(panel.getByRole('button',{name:'Export draft'}));expect(create).not.toHaveBeenCalled();expect(localStorage.getItem(b)).toBe('B protected');expect(localStorage.getItem(key('xai_task_cols'))).toBe(before);expect(panel.getByRole('alert').textContent).toContain('original account');
});
it('Tasks failed task deletion keeps the detail and original persisted record',()=>{
 render(<TasksModule lang="en"/>);fireEvent.click(document.querySelector('.task-card')!);const original=localStorage.getItem(key('xai_task_cols'));deny([key('xai_task_cols')]);fireEvent.click(within(document.querySelector('.task-detail-panel') as HTMLElement).getByRole('button',{name:'Delete'}));expect(document.querySelector('.task-detail-panel')).not.toBeNull();expect(localStorage.getItem(key('xai_task_cols'))).toBe(original);expect(screen.getByRole('alert')).toBeTruthy();
});
