import {beginAccountLocalDeletion,resumeAccountLocalDeletion,readAccountDeletionReceipt} from '../../../packages/plugin-web-settings-rest/src/internal/accountDeletionRecovery';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {ACCOUNT_LOCAL_KEYS,accountMigrationIssue} from '../../../packages/plugin-web-storage/src/index';
import {accountScope,createScopedStorage,generationMarkerKey} from '../../../packages/plugin-web-storage/src/internal/accountScope';
import {migrateAccount,rollbackAccount,readGeneration} from '../../../packages/plugin-web-storage/src/internal/accountMigration';
import {deleteAccountLocalData,exportAccountLocalData} from '../../../packages/plugin-web-storage/src/internal/accountDataLifecycle';
import '../../../packages/xai-web-tasks/src/index';
import {aiKeyStorage,aiSecretMigrationParticipant,clearAccountAiSecrets} from '../../../packages/plugin-web-ai-chat/src/internal/secretStore';
import {createDeviceIdentityStore,createIndexedDbStore} from '../../../packages/web-auth-device-session/src/index';
const assert=(v:unknown,msg:string)=>{if(!v)throw Error(msg);};
const checks:string[]=[];
assert(webShellModuleRegistrations.length>=14,'host registration map absent');
const unavailable=ACCOUNT_LOCAL_KEYS.filter(key=>(accountMigrationIssue(key,'null')??'').includes('unavailable'));

const store=createIndexedDbStore({dbName:'xai-web-ai-secrets',storeName:'secrets'});
const b64=(a:Uint8Array)=>btoa(Array.from(a,b=>String.fromCharCode(b)).join(''));
async function legacy(){const salt=crypto.getRandomValues(new Uint8Array(32)),iv=crypto.getRandomValues(new Uint8Array(12)),e=new TextEncoder();const uuid=await createDeviceIdentityStore().ensure();const base=await crypto.subtle.importKey('raw',e.encode(uuid),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,e.encode('synthetic-unowned-secret'));return JSON.stringify({version:1,kdfIterations:600000,algo:'AES-GCM',salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(ciphertext))});}
async function initialize(id:string,demo=false){const transition=accountScope.lock(id);const marker=await migrateAccount({storage:localStorage,controller:accountScope,transition,choice:'empty',demo,secrets:aiSecretMigrationParticipant});return accountScope.activate(transition,marker.generation,demo);}
async function run(){
assert(unavailable.length===0,'Production-bundled owner validators unavailable: '+unavailable.join(', '));
checks.push('all host module owner validators survive production bundling');
const task={id:'t1',title:{en:'A task',zh:'任务'},notes:'line 1\nline 2',tags:['private'],dueDate:'2026-09-09',source:{type:'board-card',boardId:'b1',listId:'l1',cardId:'c1'}};
const raw='  '+JSON.stringify(['overdue','next7','later','nodate'].map((id,i)=>({id,key:['overdue','next_7_days','later','no_date'][i],count:i===0?1:0,tasks:i===0?[task]:[],completed:[]})),null,2)+'\n';
localStorage.setItem('xai_task_cols',raw);localStorage.setItem('xai_unknown_legacy','\u0000broken {');localStorage.setItem('xai_theme','dark');
const rawSecret=await legacy();await store.setItem('anthropic',rawSecret);
let a=await initialize('A');createScopedStorage(localStorage).setItem('xai_pref_custom_private','custom-A');await aiKeyStorage.saveKey('deepseek','synthetic-A-deepseek');const before=a.generation;
const transition=accountScope.lock('A');const imported=await migrateAccount({storage:localStorage,controller:accountScope,transition,choice:'import',selectedKeys:['xai_task_cols'],secrets:aiSecretMigrationParticipant,adoptLegacySecrets:true});a=accountScope.activate(transition,imported.generation);
assert(createScopedStorage(localStorage).getItem('xai_task_cols')===raw,'import changed task bytes');assert(createScopedStorage(localStorage).getItem('xai_pref_custom_private')==='custom-A','import dropped custom owned key');assert(await aiKeyStorage.loadKey('anthropic')==='synthetic-unowned-secret','legacy BYOK adoption failed');assert(await aiKeyStorage.loadKey('deepseek')==='synthetic-A-deepseek','existing secret lost during import');assert(await store.getItem('anthropic')===rawSecret,'legacy ciphertext changed');
const archive=JSON.parse(localStorage.getItem('xai:legacy:v1:archive:'+encodeURIComponent(imported.migrationId))!);assert(archive.source.xai_task_cols===raw&&archive.source.xai_unknown_legacy==='\u0000broken {','archive raw mismatch');checks.push('complex category import and original raw/ciphertext preservation');
const failureToken=accountScope.lock('A');
const denied={get length(){return localStorage.length;},key:(n:number)=>localStorage.key(n),getItem:(k:string)=>localStorage.getItem(k),removeItem:(k:string)=>localStorage.removeItem(k),setItem:(k:string,v:string)=>{if(k===generationMarkerKey('A'))throw new DOMException('Synthetic quota failure','QuotaExceededError');localStorage.setItem(k,v);}};
let publicationRejected=false;try{await migrateAccount({storage:denied,controller:accountScope,transition:failureToken,choice:'empty',secrets:aiSecretMigrationParticipant});}catch{publicationRejected=true;}
assert(publicationRejected,'commit-marker fault was reported as success');assert(readGeneration(localStorage,'A')?.generation===imported.generation,'failed commit changed active generation');a=accountScope.activate(failureToken,imported.generation);assert(await aiKeyStorage.loadKey('anthropic')==='synthetic-unowned-secret','failed commit lost active secret');assert(localStorage.getItem('xai_task_cols')===raw&&await store.getItem('anthropic')===rawSecret,'failed commit changed legacy bytes');checks.push('failed final marker publication keeps staged content and secrets invisible');
const old=createScopedStorage(localStorage);const rollback=accountScope.lock('A');const prior=await rollbackAccount({storage:localStorage,controller:accountScope,transition:rollback});assert(prior?.generation===before,'wrong rollback generation');a=accountScope.activate(rollback,prior!.generation);assert(await aiKeyStorage.loadKey('anthropic')===null,'rollback exposed imported secret');assert(await aiKeyStorage.loadKey('deepseek')==='synthetic-A-deepseek','rollback lost previous secret');assert(createScopedStorage(localStorage).getItem('xai_task_cols')===null,'rollback exposed imported category');let revoked=false;try{old.setItem('xai_task_cols','late');}catch{revoked=true;}assert(revoked,'old generation writer accepted');checks.push('rollback restores previous generation and revokes old handles');
const saving=aiKeyStorage.saveKey('gemini','must-not-publish');const rejected=saving.then(()=>false,()=>true);const b=await initialize('B');assert(await rejected,'late crypto save accepted');assert(await aiKeyStorage.loadKey('gemini')===null,'B received late A secret');createScopedStorage(localStorage).setItem('xai_task_cols','B private');await aiKeyStorage.saveKey('deepseek','synthetic-B');checks.push('A/B isolation and pending cryptography revocation');
await initialize('A',true);assert(createScopedStorage(localStorage).getItem('xai_pref_custom_private')===null,'demo saw A');assert(await aiKeyStorage.loadKey('deepseek')===null,'demo saw A secret');checks.push('demo has independent content and BYOK generation');
const reopen=accountScope.lock('A');a=accountScope.activate(reopen,readGeneration(localStorage,'A')!.generation);assert(createScopedStorage(localStorage).getItem('xai_pref_custom_private')==='custom-A','A restore failed');const exported=exportAccountLocalData(a);assert(!Object.values(exported.records).includes('B private'),'A export includes B');
const switchB=accountScope.lock('B');accountScope.activate(switchB,b.generation!);deleteAccountLocalData(a);await clearAccountAiSecrets(a);assert(createScopedStorage(localStorage).getItem('xai_task_cols')==='B private','deleting captured A removed B');assert(await aiKeyStorage.loadKey('deepseek')==='synthetic-B','deleting A removed B secret');assert(localStorage.getItem('xai_task_cols')===raw&&await store.getItem('anthropic')===rawSecret,'delete destroyed quarantine');assert(localStorage.getItem('xai_theme')==='dark','delete removed device theme');checks.push('captured A export/deletion while B current preserves B and quarantine');
const c=await initialize('C');createScopedStorage(localStorage).setItem('xai_task_cols','C private');await aiKeyStorage.saveKey('deepseek','synthetic-C');const cHandle=createScopedStorage(localStorage);const receipt=beginAccountLocalDeletion(c);let tombstoneBlocked=false;try{cHandle.setItem('xai_task_cols','late C');}catch{tombstoneBlocked=true;}assert(tombstoneBlocked,'JSON deletion receipt did not revoke old C writes');
const backB=accountScope.lock('B');accountScope.activate(backB,b.generation!);const originalOpen=indexedDB.open.bind(indexedDB);indexedDB.open=((name:string,...args:any[])=>{if(name==='xai-web-ai-secrets')throw new DOMException('Synthetic IDB unavailable','UnknownError');return originalOpen(name,...args);}) as typeof indexedDB.open;
let cleanupFailed=false;try{await resumeAccountLocalDeletion(receipt);}catch{cleanupFailed=true;}finally{indexedDB.open=originalOpen;}
assert(cleanupFailed,'injected IDB cleanup failure reported success');assert(readAccountDeletionReceipt('C')?.phase==='local-data-cleared','failed cleanup lost durable retry phase');const complete=await resumeAccountLocalDeletion(readAccountDeletionReceipt('C')!);assert(complete.phase==='complete','local cleanup retry did not complete');assert(createScopedStorage(localStorage).getItem('xai_task_cols')==='B private'&&await aiKeyStorage.loadKey('deepseek')==='synthetic-B','retrying captured C deletion affected B');checks.push('JSON deletion tombstone and real-IDB failure retry preserve B and durable receipt');
return {pass:true,checks};}
run().then(result=>fetch('/result',{method:'POST',body:JSON.stringify(result)})).catch(error=>fetch('/result',{method:'POST',body:'FAIL '+error.stack}));
