#!/usr/bin/env bash
# roadmap_bg_run_xai-web-console_w1.sh — Wave 1 bg-script
#
# Generated by xai-roadmap-loop §3.4 Tier 2 on 2026-05-23.
# Run this OUTSIDE Claude Code (in a normal Terminal) to launch 3 parallel
# Claude Code background sessions for wave 1 of the xai-web-console roadmap.
#
# Wave 1 eligible rows (after §A4.5 dep relaxation):
#   #2 xai-web-tokens-and-i18n
#   #3 xai-web-persistence-contract
#   #4 xai-web-event-bus
#
# Row #5 (xai-web-shell) depends on 2/3/4 reaching READY_TO_SHIP. After
# this script finishes, re-run /xai-roadmap-loop mode: run to reconcile + dispatch row #5.
#
# Wave Concurrency Cap: 3 (manifest header). All 3 rows launch concurrently.
#
# Each session uses /xai-feature-full-loop with Automation Mode A-Claude and
# Verify Cross-vendor=yes (manifest defaults).
#
# Monitor with: claude agents --cwd /Users/lijinlong/Desktop/AI_Desktop/XAI_Desktop
# Truth source: packages/<slug>/docs/dev_log.md Status Panel.
# (Agent View PR dots are NOT A2K truth.)

set -euo pipefail

cd /Users/lijinlong/Desktop/AI_Desktop/XAI_Desktop

if ! command -v claude >/dev/null 2>&1; then
  echo "ERROR: 'claude' CLI not on PATH. Install Claude Code first." >&2
  exit 1
fi

echo "Launching wave 1 background sessions for xai-web-console..."
echo

# ─────────────────────────────────────────────────────────────────────────────
# Row #2 — xai-web-tokens-and-i18n
# ─────────────────────────────────────────────────────────────────────────────
claude --bg --name "roadmap-w1-xai-web-tokens-and-i18n" "$(cat <<'EOF'
/xai-feature-full-loop
Feature: xai-web-tokens-and-i18n
Automation Mode: A-Claude
Verify Cross-vendor: yes
Requirement: Per docs/reviews/xai-web-tokens-and-i18n/20260523-roadmap-seed.md — port web design/tokens.css (CSS variables: surface, text, accent, semantic, label, list-column, font, spacing, radius, shadow, density, motion) and web design/i18n.js (EN + 中文 strings + MOCK data) into apps/web/src/styles/ + a typed useI18n hook colocated with the shell or in a shared package, per ADR-0007 (docs/adr/0007-xai-web-console-build-form.md) port mapping table. Token names + oklch values MUST match DESIGN.md §5 verbatim; i18n key paths MUST preserve I18N.en.module.key shape; light/dark/system + density + font-scale + accent-hue MUST be data-* driven exactly as web design/app.jsx. Acceptance: tokens.css imports cleanly, useI18n returns t and s(path) matching the Babel-form behavior, smoke route renders EN and 中文 with correct font stack.
EOF
)"
echo "  ✓ Row #2 dispatched"
echo

# ─────────────────────────────────────────────────────────────────────────────
# Row #3 — xai-web-persistence-contract
# ─────────────────────────────────────────────────────────────────────────────
claude --bg --name "roadmap-w1-xai-web-persistence-contract" "$(cat <<'EOF'
/xai-feature-full-loop
Feature: xai-web-persistence-contract
Automation Mode: A-Claude
Verify Cross-vendor: yes
Requirement: Per docs/reviews/xai-web-persistence-contract/20260523-roadmap-seed.md — stand up a typed localStorage key registry that owns every xai_* key listed in DESIGN.md §9.2 (24 keys: accent_hue, rail_pos, bg_tone, rail_order, pet_pos, pet_id, task_cols, boards_v2, active_board, board_panels, board_inbox, dash_order, clock_style, clock_tz, zones, ai_convos, ai_insights, ai_voice, pref_*, plus pomodoro_sessions and countdowns proposed in ADR-0007 S8). Provide a single usePref<T>(key, default) hook used by every module + xai_pref_* autosaver for Settings. Hook MUST be SSR-safe. Provide a single import path. Acceptance: every key in §9.2 has a typed entry, hook compiles, smoke test stores+reads, SSR import does not throw.
EOF
)"
echo "  ✓ Row #3 dispatched"
echo

# ─────────────────────────────────────────────────────────────────────────────
# Row #4 — xai-web-event-bus
# ─────────────────────────────────────────────────────────────────────────────
claude --bg --name "roadmap-w1-xai-web-event-bus" "$(cat <<'EOF'
/xai-feature-full-loop
Feature: xai-web-event-bus
Automation Mode: A-Claude
Verify Cross-vendor: yes
Requirement: Per docs/reviews/xai-web-event-bus/20260523-roadmap-seed.md — provide a typed event bus + minimal shared store for cross-module signaling so module-to-module interaction does not go through direct imports (per CLAUDE.md Plugin-to-plugin → @repo/core/events rule + ADR-0007 S7). Must support goTo(moduleId) navigation, Settings → live theme/density/accent/rail-pos broadcast, Dashboard mini-cal → Calendar deep-link, pet-on toggle. Reuse @repo/core/events where it fits; if a Web-specific module is cleaner, document the choice in ADR-0007 follow-up. Event payloads MUST be typed (no any). No module direct-imports another's internals; bus is the only cross-module surface. Acceptance: two module placeholders subscribe+emit, unit test asserts payload typing, unused listener cleans up correctly.
EOF
)"
echo "  ✓ Row #4 dispatched"
echo

echo "─────────────────────────────────────────────────────────────"
echo "Wave 1 dispatch complete — 3 background sessions launched."
echo
echo "Monitor with:"
echo "  claude agents --cwd /Users/lijinlong/Desktop/AI_Desktop/XAI_Desktop"
echo
echo "Truth source: packages/<slug>/docs/dev_log.md Status Panel."
echo "  - tokens-and-i18n:      packages/xai-web-tokens-and-i18n/docs/dev_log.md"
echo "  - persistence-contract: packages/xai-web-persistence-contract/docs/dev_log.md"
echo "  - event-bus:            packages/xai-web-event-bus/docs/dev_log.md"
echo
echo "When all 3 reach READY_TO_SHIP, return to a Claude Code window and run:"
echo "  /xai-roadmap-loop"
echo "  mode: run"
echo "  manifest: docs/workflow/roadmap/xai-web-console.md"
echo "  dispatch: bg"
echo "→ reconcile picks up the READY_TO_SHIP state, row #5 (xai-web-shell)"
echo "  becomes eligible (deps 2/3/4 satisfied via ready_to_ship semantics),"
echo "  and is dispatched as wave 1b."
echo
echo "OPTIONAL — if you have ship gates after wave 1: run the ship agent for"
echo "each row first, then re-run roadmap-loop."
