import {it,expect,vi} from 'vitest';
import {renderHook,act} from '@testing-library/react';
import {accountScope} from '@repo/plugin-web-storage';
import {subscribeSameTab} from '../../../packages/plugin-web-storage/src/internal/storage.js';
import {useUserCalEvents} from '../../../packages/xai-web-calendar/src/internal/eventStore/useUserCalEvents.js';
const event=(title:string)=>({title,startISO:'2026-05-22T09:00',endISO:'2026-05-22T10:00',colorPreset:'mint' as const,recurrence:null});
const original={id:'original',...event('Original'),createdAt:'2026-05-22T00:00:00Z',updatedAt:'2026-05-22T00:00:00Z'};
const receipt={operationVersion:1,signature:'prior',result:{ok:true,targetId:'original'},committedAt:'2026-09-09T00:00:00Z'};
const key=()=>accountScope.physicalKey('xai_calendar_events');
function seed(){const raw=JSON.stringify({format:'xai-command-state',version:1,revision:3,data:{original},receipts:{prior:receipt}});localStorage.setItem(key(),raw);return raw;}
it('actual Calendar hooks receive exactly one domain publication per create/update/delete without legacy setter warnings',async()=>{seed();const a=renderHook(()=>useUserCalEvents()),b=renderHook(()=>useUserCalEvents());const published=vi.fn();const unsubscribe=subscribeSameTab('xai_calendar_events',published);const warn=vi.spyOn(console,'warn'),writes=vi.spyOn(Storage.prototype,'setItem');try{let created:any;await act(async()=>{created=await a.result.current.create(event('Created'));});expect(created).not.toBeNull();expect(a.result.current.getById(created.id)?.title).toBe('Created');expect(b.result.current.getById(created.id)?.title).toBe('Created');expect(published).toHaveBeenCalledTimes(1);await act(async()=>{expect(await a.result.current.update(created.id,{title:'Edited'},created)).not.toBeNull();});expect(b.result.current.getById(created.id)?.title).toBe('Edited');expect(published).toHaveBeenCalledTimes(2);await act(async()=>{expect(await b.result.current.remove(created.id)).toBe(true);});expect(a.result.current.getById(created.id)).toBeNull();expect(b.result.current.getById(created.id)).toBeNull();expect(published).toHaveBeenCalledTimes(3);expect(writes.mock.calls.filter(([k])=>k===key())).toHaveLength(3);expect(JSON.parse(localStorage.getItem(key())!).receipts).toEqual({prior:receipt});expect(a.result.current.getById('original')).toEqual(original);expect(warn.mock.calls.filter(args=>args.some(v=>String(v).includes('refusing legacy write')))).toHaveLength(0);}finally{unsubscribe();writes.mockRestore();warn.mockRestore();}});
it('failed Calendar commit publishes nothing and preserves both hook projections',async()=>{const raw=seed();const a=renderHook(()=>useUserCalEvents()),b=renderHook(()=>useUserCalEvents()),publish=vi.fn(),unsubscribe=subscribeSameTab('xai_calendar_events',publish),physical=key(),native=Storage.prototype.setItem;const fault=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(k,v){if(k===physical)throw new DOMException('quota','QuotaExceededError');native.call(this,k,v);});try{await act(async()=>{expect(await a.result.current.update('original',{title:'Failed'},original)).toBeNull();});expect(localStorage.getItem(physical)).toBe(raw);expect(a.result.current.events).toEqual({original});expect(b.result.current.events).toEqual({original});expect(publish).not.toHaveBeenCalled();}finally{fault.mockRestore();unsubscribe();}});
