import { createTestLockManager } from "../../../packages/xai-web-tasks/src/__tests__/webLocksHarness.js";
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,screen,within,fireEvent,act,waitFor,cleanup} from '@testing-library/react';
import {accountScope,generationMarkerKey,setCanonicalCommandActivationForTests} from '@repo/plugin-web-storage';
import {TasksModule} from '../../../packages/xai-web-tasks/src/TasksModule.js';
import {TaskComposer} from '../../../packages/xai-web-tasks/src/TaskComposer.js';
import {DEFAULT_TASK_LISTS,DEFAULT_TASK_TAGS} from '../../../packages/xai-web-tasks/src/internal/taskMeta.js';
const key=()=>accountScope.physicalKey('xai_task_cols');
const meta=(kind:string)=>accountScope.physicalKey('xai_pref_task_'+kind);
const receipt={operationVersion:1,signature:'retained',result:{ok:true,targetId:'t1'},committedAt:'2026-09-09T00:00:00Z'};
const row=(id:string,title:string)=>({id,title:{en:title,zh:title},tag:'study',tags:['study'],priority:'normal',listId:'inbox'});
const cols=(tasks:any[]=[row('t1','Original'),row('t2','Second')])=>[{id:'overdue',key:'overdue',count:0,tasks:[]},{id:'next7',key:'next_7_days',count:0,tasks:[]},{id:'later',key:'later',count:0,tasks:[]},{id:'nodate',key:'no_date',count:tasks.length,tasks}];
const envelope=(tasks:any[]=[row('t1','Original'),row('t2','Second')],revision=1)=>JSON.stringify({format:'xai-command-state',version:1,revision,data:cols(tasks),receipts:{prior:receipt}});
const data=()=>JSON.parse(localStorage.getItem(key())!);
const rows=()=>data().data.flatMap((c:any)=>[...c.tasks,...(c.completed??[])]);
const panel=()=>screen.getByLabelText('Task details');
const title=()=>within(panel()).getByLabelText('Title') as HTMLInputElement;
const save=()=>fireEvent.click(within(panel()).getByRole('button',{name:'Save'}));
async function mount(){localStorage.setItem(key(),envelope());render(<TasksModule lang="en"/>);await act(async()=>{});}
function open(index=0){fireEvent.click(document.querySelectorAll('.task-card')[index]!);}
function deferredLock(){let release!:()=>void;const gate=new Promise<void>(r=>release=r);const request=vi.fn(async(_name:string,run:()=>unknown)=>{await gate;return run();});vi.stubGlobal('navigator',{locks:createTestLockManager(request)});return {release,request};}
async function external(raw:string){await act(async()=>{localStorage.setItem(key(),raw);window.dispatchEvent(new StorageEvent('storage',{key:key(),newValue:raw,storageArea:localStorage}));});}
function quota(){const physical=key(),native=Storage.prototype.setItem;return vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(k,v){if(k===physical)throw new DOMException('quota','QuotaExceededError');native.call(this,k,v);});}
beforeEach(()=>{localStorage.clear();accountScope.activate(accountScope.lock('tasks-review'),'g1');localStorage.setItem(generationMarkerKey('tasks-review'),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));setCanonicalCommandActivationForTests(true);vi.stubGlobal('navigator',{locks:createTestLockManager()});vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date(2026,8,9,12));HTMLDialogElement.prototype.showModal=function(){this.open=true};HTMLDialogElement.prototype.close=function(){this.open=false};});
afterEach(()=>{cleanup();setCanonicalCommandActivationForTests(false);vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();});
it('valid empty envelope remains empty, retains receipts, and avoids seed writes',async()=>{const raw=envelope([]);localStorage.setItem(key(),raw);const spy=vi.spyOn(Storage.prototype,'setItem');render(<TasksModule lang="en"/>);await act(async()=>{});expect(localStorage.getItem(key())).toBe(raw);expect(document.querySelectorAll('.task-card')).toHaveLength(0);expect(spy.mock.calls.filter(([k])=>k===key())).toHaveLength(0);});
it.each(['null','{bad',JSON.stringify({bad:'shape'}),JSON.stringify({format:'xai-command-state',version:1,revision:1,data:null,receipts:{}})])('invalid present %s refuses normalization without loss',async raw=>{localStorage.setItem(key(),raw);render(<TasksModule lang="en"/>);await screen.findByRole('alert');expect(localStorage.getItem(key())).toBe(raw);});
it.each([false,true])('detail stale draft must not overwrite observed newer target; prior quota=%s',async failed=>{
 await mount();open();fireEvent.change(title(),{target:{value:'My unsaved title'}});
 if(failed){const fault=quota();save();await within(panel()).findByRole('alert');fault.mockRestore();}
 const raw=envelope([row('t1','External title'),row('t2','Second')],9);await external(raw);expect(title().value).toBe('My unsaved title');save();await act(async()=>{});console.log('stale-detail',JSON.stringify({failed,preserved:localStorage.getItem(key())===raw,actual:rows().find((t:any)=>t.id==='t1').title.en}));expect.soft(localStorage.getItem(key())).toBe(raw);expect(within(panel()).queryByRole('alert')).not.toBeNull();expect(title().value).toBe('My unsaved title');
});
it('queued detail save checks its baseline, keeps latest form, and refuses external change',async()=>{await mount();open();fireEvent.change(title(),{target:{value:'Queued draft'}});const g=deferredLock();save();expect((within(panel()).getByRole('button',{name:'Save'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(title(),{target:{value:'Latest unsaved form'}});const raw=envelope([row('t1','External title'),row('t2','Second')],9);localStorage.setItem(key(),raw);await act(async()=>g.release());await within(panel()).findByRole('alert');expect(localStorage.getItem(key())).toBe(raw);expect(title().value).toBe('Latest unsaved form');});
it('queued missing detail target leaves the failed draft visibly recoverable',async()=>{await mount();open();fireEvent.change(title(),{target:{value:'Keep missing-target draft'}});const g=deferredLock();save();const raw=envelope([row('t2','Second')],9);await external(raw);await act(async()=>g.release());expect(localStorage.getItem(key())).toBe(raw);console.log('missing-detail',JSON.stringify({panel:!!screen.queryByLabelText('Task details'),alert:!!screen.queryByRole('alert'),draftVisible:document.body.textContent?.includes('Keep missing-target draft')}));expect(screen.queryByRole('alert')).not.toBeNull();expect(document.querySelector('.task-detail-panel input')?.getAttribute('value')).toBe('Keep missing-target draft');});
it('actual detail duplicate save is pending once and preserves receipts',async()=>{await mount();open();fireEvent.change(title(),{target:{value:'Once'}});const g=deferredLock();save();save();expect(g.request).toHaveBeenCalledTimes(1);await act(async()=>g.release());await waitFor(()=>expect(rows().find((t:any)=>t.id==='t1').title.en).toBe('Once'));expect(data().receipts).toEqual({prior:receipt});expect((within(panel()).getByRole('button',{name:'Save'}) as HTMLButtonElement).disabled).toBe(false);});
it('old pending create completion keeps a newly opened composer draft',async()=>{await mount();fireEvent.click(screen.getByRole('button',{name:'New task'}));const input=()=>document.getElementById('task-composer-title-input') as HTMLInputElement;fireEvent.change(input(),{target:{value:'Old create'}});const g=deferredLock();fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Add'}));fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Cancel'}));fireEvent.click(screen.getByRole('button',{name:'New task'}));fireEvent.change(input(),{target:{value:'New unsaved create'}});await act(async()=>g.release());await waitFor(()=>expect(rows().some((t:any)=>t.title.en==='Old create')).toBe(true));expect((document.querySelector('dialog') as HTMLDialogElement).open).toBe(true);expect(input().value).toBe('New unsaved create');});
it('composer catches actual rejected Promise and retains retryable draft',async()=>{const callback=vi.fn().mockRejectedValueOnce(Error('async reject')).mockResolvedValueOnce(true);render(<TaskComposer open defaultBucket="nodate" lang="en" onSave={callback} onClose={()=>{}}/>);const input=document.getElementById('task-composer-title-input') as HTMLInputElement;fireEvent.change(input,{target:{value:'Retained'}});fireEvent.click(screen.getByRole('button',{name:'Add'}));await screen.findByRole('alert');expect(input.value).toBe('Retained');fireEvent.click(screen.getByRole('button',{name:'Add'}));await waitFor(()=>expect(screen.queryByRole('alert')).toBeNull());expect(callback).toHaveBeenCalledTimes(2);});
it('queued old-owner detail save refuses both account records',async()=>{await mount();open();fireEvent.change(title(),{target:{value:'A only'}});const aKey=key(),before=localStorage.getItem(aKey),g=deferredLock();save();accountScope.activate(accountScope.lock('B'),'g2');localStorage.setItem(generationMarkerKey('B'),JSON.stringify({generation:'g2',migrationId:'B',previous:null}));await act(async()=>g.release());expect(localStorage.getItem(aKey)).toBe(before);expect(localStorage.getItem(key())).toBeNull();});
it.each(['list','tag'])('actual %s cascade waits for Task write and preserves metadata on failure',async kind=>{
 localStorage.setItem(meta('lists'),JSON.stringify(DEFAULT_TASK_LISTS));localStorage.setItem(meta('tags'),JSON.stringify(DEFAULT_TASK_TAGS));await mount();const metadata=meta(kind==='list'?'lists':'tags'),before=localStorage.getItem(metadata),g=deferredLock(),fault=quota();fireEvent.click(screen.getAllByRole('button',{name:kind==='list'?'Delete list':'Delete tag'})[0]!);expect(localStorage.getItem(metadata)).toBe(before);await act(async()=>g.release());await screen.findByRole('alert');expect(localStorage.getItem(metadata)).toBe(before);fault.mockRestore();fireEvent.click(screen.getAllByRole('button',{name:kind==='list'?'Delete list':'Delete tag'})[0]!);await waitFor(()=>expect(localStorage.getItem(metadata)).not.toBe(before));expect(rows().every((t:any)=>kind==='list'?t.listId!=='inbox':!t.tags.includes('study'))).toBe(true);expect(data().receipts).toEqual({prior:receipt});
});
it('old bulk-delete completion must preserve newer selection and detail session',async()=>{await mount();const selections=screen.getAllByRole('checkbox',{name:'Select task'});fireEvent.click(selections[0]!);open();const g=deferredLock();fireEvent.click(within(screen.getByRole('region',{name:'Bulk actions'})).getByRole('button',{name:'Delete'}));fireEvent.click(within(panel()).getByRole('button',{name:'Close'}));fireEvent.click(within(screen.getByRole('region',{name:'Bulk actions'})).getByRole('button',{name:'Clear'}));fireEvent.click(screen.getAllByRole('checkbox',{name:'Select task'})[1]!);open(1);await act(async()=>g.release());expect(rows().map((t:any)=>t.id)).toEqual(['t2']);console.log('bulk-new-session',JSON.stringify({panel:!!screen.queryByLabelText('Task details'),selected:!!screen.queryByRole('region',{name:'Bulk actions'})}));expect.soft(screen.queryByLabelText('Task details')).not.toBeNull();expect(screen.queryByRole('region',{name:'Bulk actions'})).not.toBeNull();});
it.each(['list','tag'])('deleting %s metadata must also reassign references in valid completed storage',async kind=>{
 localStorage.setItem(meta('lists'),JSON.stringify(DEFAULT_TASK_LISTS));localStorage.setItem(meta('tags'),JSON.stringify(DEFAULT_TASK_TAGS));const parsed=JSON.parse(envelope([]));parsed.data[3].completed=[{...row('completed','Completed row'),done:true}];localStorage.setItem(key(),JSON.stringify(parsed));render(<TasksModule lang="en"/>);await act(async()=>{});
 fireEvent.click(screen.getAllByRole('button',{name:kind==='list'?'Delete list':'Delete tag'})[0]!);await act(async()=>{});await waitFor(()=>expect(JSON.parse(localStorage.getItem(meta(kind==='list'?'lists':'tags'))!).some((v:any)=>v.id===(kind==='list'?'inbox':'study'))).toBe(false));
 const completed=rows().find((t:any)=>t.id==='completed');console.log('completed-cascade',JSON.stringify({kind,completed}));expect(completed.done).toBe(true);expect(data().receipts).toEqual({prior:receipt});if(kind==='list')expect(completed.listId).not.toBe('inbox');else expect(completed.tags).not.toContain('study');
});
