import React from 'react';
import {it,expect,vi} from 'vitest';
import {act,fireEvent,render,within} from '@testing-library/react';
import {smartListsPane} from '../../../packages/plugin-web-settings-rest/src/panes/smartListsPane';
import {fixture,key,owner,logical,activate,nativeGet,nativeSet,mount,choose,select,flush,seed,external,hold,quota,retry,reload} from '../web-d2-smart-lists-astra/fixture';
fixture();
const unload=()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;};
function capture(){const blobs:Blob[]=[];const clicks:string[]=[];vi.stubGlobal('URL',class extends URL{static createObjectURL(b:Blob){blobs.push(b);return 'blob:draft';}static revokeObjectURL(){}});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(function(this:HTMLAnchorElement){clicks.push(this.download);});return {blobs,clicks,async json(){expect(blobs).toHaveLength(1);return JSON.parse(await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=reject;f.readAsText(blobs[0]!);}));}};}
const exportClick=(ui:ReturnType<typeof mount>)=>fireEvent.click(ui.q.getByRole('button',{name:/export/i}));
it('actual latest complete Blob retains own prototype fields under total storage denial and does not clear recovery',async()=>{const raw='{"extension":"future","__proto__":"data","constructor":"safe"}';seed(raw);const ui=mount();await flush();quota();choose(ui,0,'hide');await flush();choose(ui,1,'if-not-empty');await flush();const c=capture();vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw Error('denied reads');});exportClick(ui);expect(c.clicks).toEqual(['smart-lists-draft.json']);expect(await c.json()).toEqual({version:1,kind:'smart-lists-draft',values:{...JSON.parse(raw),all:'hide',today:'if-not-empty'}});expect(ui.q.queryByRole('alert')).not.toBeNull();expect(unload()).toBe(true);expect(nativeGet.call(localStorage,key)).toBe(raw);});
for(const step of ['Blob','URL','click'])it(`export ${step} exception retains draft, original recovery, and departure guard`,async()=>{seed('{}');const ui=mount();await flush();quota();choose(ui,0,'hide');await flush();const c=capture();if(step==='Blob')vi.stubGlobal('Blob',class{constructor(){throw Error('Blob');}});else if(step==='URL')vi.spyOn(URL,'createObjectURL').mockImplementation(()=>{throw Error('URL');});else vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{throw Error('click');});exportClick(ui);expect(ui.q.getByRole('alert').textContent).toMatch(/export.*failed|could not.*export/i);expect(select(ui).value).toBe('hide');expect(unload()).toBe(true);expect(nativeGet.call(localStorage,key)).toBe('{}');expect(c.clicks).toHaveLength(0);});
it('beforeunload clean/invalid mount false, pending true, explicit conflict discard false',async()=>{seed('null');let ui=mount();await flush();expect(unload()).toBe(false);expect(ui.q.queryByRole('button',{name:/export/i})).toBeNull();ui.unmount();seed('{}');ui=mount();await flush();expect(unload()).toBe(false);const release=await hold();choose(ui,0,'hide');await flush();expect(unload()).toBe(true);act(()=>external('{"today":"hide"}'));await release();expect(unload()).toBe(true);const c=capture();exportClick(ui);expect((await c.json()).values).toEqual({all:'hide'});reload(ui);await flush();expect(unload()).toBe(false);expect(nativeGet.call(localStorage,key)).toBe('{"today":"hide"}');});
it('uncertain own commit exports actual intention and verified Retry clears unload',async()=>{seed('{}');const ui=mount();await flush();let armed=false,writes=0;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){nativeSet.call(this,k,v);if(k===key){armed=true;writes++;}});vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,k){if(k===key&&armed){armed=false;throw Error('readback');}return nativeGet.call(this,k);});choose(ui,1,'hide');await flush();const c=capture();exportClick(ui);expect((await c.json()).values).toEqual({today:'hide'});expect(unload()).toBe(true);retry(ui);await flush();expect(unload()).toBe(false);expect(writes).toBe(1);});
it('owner changes inside object URL creation revoke without clicking',async()=>{seed('{}');const ui=mount();await flush();quota();choose(ui,0,'hide');await flush();const c=capture();const revoke=vi.spyOn(URL,'revokeObjectURL');vi.spyOn(URL,'createObjectURL').mockImplementation(()=>{activate('export-B');return 'blob:stale';});await act(async()=>exportClick(ui));expect(c.clicks).toHaveLength(0);expect(revoke).toHaveBeenCalledWith('blob:stale');expect(select(ui).value).toBe('show');});
it('retained A guard capability cannot export or discard a later B draft',async()=>{seed('{}');let guard:any;const rendered=render(smartListsPane.render({lang:'en',registerDepartureGuard:(g)=>{guard=g;return()=>{};}}));const ui={...rendered,q:within(rendered.container)};await flush();vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k.endsWith(logical))throw Error('quota');nativeSet.call(this,k,v);});choose(ui,0,'hide');await flush();const old=guard;await act(async()=>activate('guard-B'));choose(ui,1,'hide');await flush();const c=capture();expect.soft(old.isCurrent()).toBe(false);await act(async()=>{old.exportDraft();old.discardDraft();});expect.soft(c.clicks).toHaveLength(0);expect(select(ui,1).value).toBe('hide');expect(unload()).toBe(true);});
