import React from 'react';
import {it,expect,vi,beforeEach} from 'vitest';
import {transferableAbortController} from 'node:util';
import {act,cleanup,fireEvent,render,within} from '@testing-library/react';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider} from '@repo/xai-web-shell';
import {composedSettingsRegistration} from '../../../apps/web/src/routes/modules/composedSettingsRegistration';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {fixture,key,logical,nativeGet,nativeSet,activate,choose,select,flush,seed,quota,hold} from '../web-d2-smart-lists-astra/fixture';
fixture();
// Match Node Request with a native AbortController; jsdom AbortSignal is a different realm.
beforeEach(()=>{vi.stubGlobal('AbortController',transferableAbortController().constructor);});
const smart='/app/settings/smart_lists',notifications='/app/settings/notifications';
async function host(pending=false){seed('{"extension":"A"}');const Composed=composedSettingsRegistration.children[0]!.render;const router=createMemoryRouter([{path:'/app/settings/*',element:<Composed/>},{path:'/app/dashboard',element:<div>Dashboard route</div>}],{initialEntries:['/app/dashboard',smart],initialIndex:1});const ui0=render(<WebShellProvider modules={[composedSettingsRegistration]} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);const ui={...ui0,q:within(ui0.container)};await flush();const failure=pending?null:quota();choose(ui,0,'hide');await flush();return{ui,router,failure};}
const navigate=async(router:any,to:any)=>{await act(async()=>{await router.navigate(to);});await flush();};
const click=(ui:any,name:RegExp)=>fireEvent.click(ui.q.getByRole('button',{name}));
it('programmatic second destination cannot replace first blocked intent',async()=>{const {ui,router}=await host();await navigate(router,notifications);expect(ui.q.queryByRole('dialog')).not.toBeNull();await navigate(router,'/app/settings/date_time');click(ui,/Discard local changes and leave/);await flush();expect(router.state.location.pathname).toBe(notifications);});
it('Back keeps original pane, Stay retains map; later discard permits Back once',async()=>{const {ui,router}=await host();await navigate(router,-1);expect(router.state.location.pathname).toBe(smart);expect(select(ui).value).toBe('hide');click(ui,/^Stay$/);await flush();expect(router.state.location.pathname).toBe(smart);await navigate(router,-1);click(ui,/Discard local changes and leave/);await flush();expect(router.state.location.pathname).toBe('/app/dashboard');expect(nativeGet.call(localStorage,key)).toBe('{"extension":"A"}');});
it('dialog traps Tab within controls and Escape returns prior focus',async()=>{const {ui,router}=await host();const first=select(ui);first.focus();await navigate(router,notifications);const dialog=ui.q.getByRole('dialog');expect(dialog.contains(document.activeElement)).toBe(true);const buttons=within(dialog).getAllByRole('button');buttons.at(-1)!.focus();const e=new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true});act(()=>buttons.at(-1)!.dispatchEvent(e));expect.soft(document.activeElement).toBe(buttons[0]);fireEvent.keyDown(dialog,{key:'Escape'});await flush();expect(ui.q.queryByRole('dialog')).toBeNull();expect(document.activeElement).toBe(first);});
it('sign-out first rejects concurrent route departure instead of allowing both',async()=>{const {ui,router}=await host();let outcome:unknown;await act(async()=>{void requestSettingsDeparture('sign-out').then(x=>outcome=x);});await navigate(router,notifications);click(ui,/Discard local changes and leave/);await flush();expect(outcome).toBe(true);expect(router.state.location.pathname).toBe(smart);});
it('route first rejects competing sign-out and permits only original route',async()=>{const {ui,router}=await host();await navigate(router,notifications);let outcome:unknown;await act(async()=>{void requestSettingsDeparture('sign-out').then(x=>outcome=x);});click(ui,/Discard local changes and leave/);await flush();expect(outcome).toBe(false);expect(router.state.location.pathname).toBe(notifications);});
it('same sign-out request is single-flight; Stay resolves all false',async()=>{const {ui}=await host();let a!:Promise<boolean>,b!:Promise<boolean>;await act(async()=>{a=requestSettingsDeparture('sign-out');b=requestSettingsDeparture('sign-out');});expect(a).toBe(b);click(ui,/^Stay$/);await flush();expect(await a).toBe(false);expect(await b).toBe(false);});
it('owner change cancels queued sign-out without requiring user action',async()=>{const {ui}=await host();let outcome:unknown;await act(async()=>{void requestSettingsDeparture('sign-out').then(x=>outcome=x);});await act(async()=>activate('host-B'));await flush();expect.soft(outcome).toBe(false);expect(ui.q.queryByRole('dialog')).toBeNull();});
it('old sign-out intent cannot discard B newly edited draft',async()=>{const {ui,failure}=await host();let outcome:unknown;await act(async()=>{void requestSettingsDeparture('sign-out').then(x=>outcome=x);});failure!.mockRestore();vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k.endsWith(logical))throw Error('quota');nativeSet.call(this,k,v);});await act(async()=>activate('new-draft-B'));choose(ui,1,'hide');await flush();if(ui.q.queryByRole('dialog'))click(ui,/Discard local changes and leave/);await flush();expect.soft(outcome).toBe(false);expect(select(ui,1).value).toBe('hide');});
it('unmount cancels sign-out Promise and unregisters delegate',async()=>{const {ui}=await host();let p!:Promise<boolean>;await act(async()=>{p=requestSettingsDeparture('sign-out');});ui.unmount();expect(await p).toBe(false);expect(await requestSettingsDeparture('sign-out')).toBe(true);});
it('pending current map can export in dialog; successful latest save releases original requested navigation',async()=>{seed('{}');const release=await hold();const {ui,router}=await host(true);await navigate(router,notifications);let blob:Blob|undefined;vi.stubGlobal('URL',class extends URL{static createObjectURL(b:Blob){blob=b;return'blob:pending';}static revokeObjectURL(){}});const clickSpy=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});click(ui,/Export current draft/);expect(blob).toBeDefined();expect(clickSpy).toHaveBeenCalledTimes(1);expect(router.state.location.pathname).toBe(smart);await release();await flush();expect(JSON.parse(nativeGet.call(localStorage,key)!)).toEqual({extension:'A',all:'hide'});expect(router.state.location.pathname).toBe(notifications);});
