import React from 'react';
import {it,expect,vi,beforeEach,afterEach} from 'vitest';
import {act,cleanup,fireEvent,render,within} from '@testing-library/react';
import {transferableAbortController} from 'node:util';
import {createMemoryRouter,RouterProvider} from 'react-router';
import {WebShellProvider,Shell} from '@repo/xai-web-shell';
import {accountScope,generationMarkerKey,prefMutationLockName} from '@repo/plugin-web-storage';
import {webShellModuleRegistrations} from '../../../apps/web/src/routes/modules/shellRegistrations';
import {composedSettingsRegistration} from '../../../apps/web/src/routes/modules/composedSettingsRegistration';
import {requestSettingsDeparture} from '../../../apps/web/src/routes/modules/settingsDeparture';
import {createTestLockManager} from '../web-board-workspace-astra-review/named-lock-fixture';
const nativeSet=Storage.prototype.setItem,nativeGet=Storage.prototype.getItem;
const keys=['xai_pref_dt_start_week','xai_pref_dt_lunar','xai_pref_dt_week_numbers','xai_pref_dt_holidays','xai_pref_dt_timezone'];
const pane='/app/settings/date_time',next='/app/settings/notifications';
async function flush(){await act(async()=>{for(let i=0;i<8;i++)await new Promise(r=>setTimeout(r,0));});}
beforeEach(()=>{localStorage.clear();const owner='date-time-parent-A';nativeSet.call(localStorage,generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');keys.forEach((key,i)=>nativeSet.call(localStorage,key,i===0?'monday':'true'));vi.stubGlobal('AbortController',transferableAbortController().constructor);vi.stubGlobal('navigator',{locks:createTestLockManager()});vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});vi.stubGlobal('requestAnimationFrame',(cb:FrameRequestCallback)=>setTimeout(()=>cb(performance.now()),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
async function host(initialEntries=[pane],initialIndex=initialEntries.length-1){const Composed=composedSettingsRegistration.children[0]!.render;const router=createMemoryRouter([{path:'/app',element:<Shell lang="en" setLang={()=>{}} theme="light" setTheme={()=>{}} density="comfortable" setDensity={()=>{}}/>,children:[{path:'settings/*',element:<Composed/>},{path:'dashboard',element:<div>Dashboard destination</div>},{path:'tasks',element:<div>Tasks destination</div>}]}],{initialEntries,initialIndex});const ui=render(<WebShellProvider modules={webShellModuleRegistrations} lang="en" railPos="left" petOn={false} setPetOn={()=>{}}><RouterProvider router={router}/></WebShellProvider>);await flush();const element=ui.container.querySelector('.dt-pane')!;expect(element).toBeTruthy();const q=within(element as HTMLElement);expect((q.getByRole('combobox') as HTMLSelectElement).value).toBe('monday');expect(q.getAllByRole('switch').map(e=>e.getAttribute('aria-checked'))).toEqual(['true','true','true','true']);return {ui,q,router};}
function deny(index:number){vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===keys[index])throw Error('quota');nativeSet.call(this,k,v);});}
function change(q:ReturnType<typeof within>,index:number){if(index===0)fireEvent.change(q.getByRole('combobox'),{target:{value:'sunday'}});else fireEvent.click(q.getAllByRole('switch')[index-1]);}

const dialog=(ui:ReturnType<typeof render>)=>within(ui.getByRole('dialog'));
async function failed(){const h=await host();deny(1);change(h.q,1);await flush();return h;}
function ownerB(){const owner='date-time-parent-B';nativeSet.call(localStorage,generationMarkerKey(owner),JSON.stringify({generation:'g1',migrationId:'fixture',previous:null}));accountScope.activate(accountScope.lock(owner),'g1');}
async function hold(index:number){let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);const done=navigator.locks.request(prefMutationLockName(keys[index]),{mode:'exclusive'},()=>{entered();return gate});await ready;return async()=>{release();await done;await flush();};}
it.each(['sidebar','rail'])('actual %s producer holds and current discard leaves without writes',async producer=>{const {ui,q,router}=await failed();const writes=vi.spyOn(Storage.prototype,'removeItem');if(producer==='sidebar')fireEvent.click(within(ui.container.querySelector('.settings-sidebar') as HTMLElement).getByRole('button',{name:'Notifications'}));else fireEvent.click(ui.container.querySelector('.app-rail [aria-label="Tasks"]')!);await flush();expect(router.state.location.pathname).toBe(pane);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(producer==='sidebar'?next:'/app/tasks');expect(nativeGet.call(localStorage,keys[1])).toBe('true');expect(writes).not.toHaveBeenCalled();});
it('first route beats same-turn route and signout; Stay retains work',async()=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{void router.navigate(next);void router.navigate('/app/dashboard');void requestSettingsDeparture('sign-out').then(x=>out=x);});await flush();expect(router.state.location.pathname).toBe(pane);expect(out).toBe(false);fireEvent.click(dialog(ui).getByRole('button',{name:'Stay'}));await flush();expect(ui.queryByRole('dialog')).toBeNull();expect(q.getAllByRole('switch')[0].getAttribute('aria-checked')).toBe('false');act(()=>{void router.navigate(next);void router.navigate('/app/dashboard');});await flush();fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(next);});
it('first signout beats same-turn route; Escape declines without losing work',async()=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{void requestSettingsDeparture('sign-out').then(x=>out=x);void router.navigate(next);});await flush();expect(out).toBe('pending');expect(router.state.location.pathname).toBe(pane);fireEvent.keyDown(ui.getByRole('dialog'),{key:'Escape'});await flush();expect(out).toBe(false);expect(router.state.location.pathname).toBe(pane);expect(q.getAllByRole('switch')[0].getAttribute('aria-checked')).toBe('false');});
it.each([-1,1])('numeric history %s stays held then replays exact destination',async delta=>{const entries=delta===-1?['/app/dashboard',pane]:[pane,'/app/dashboard'];const {ui,q,router}=await host(entries,delta===-1?1:0);deny(1);change(q,1);await flush();act(()=>{void router.navigate(delta)});await flush();expect(router.state.location.pathname).toBe(pane);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe('/app/dashboard');});
it('path-relative navigation preserves the actual relative destination',async()=>{const {ui,router}=await failed();act(()=>{void router.navigate('../notifications',{relative:'path'})});await flush();expect(router.state.location.pathname).toBe(pane);fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe(next);});
it('partial Retry cannot release intent; all latest verified clean releases once',async()=>{const {ui,q,router}=await host();let denied=true;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(denied&&keys.includes(k))throw Error('quota');nativeSet.call(this,k,v);});change(q,0);change(q,1);await flush();act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(pane);denied=false;fireEvent.click(q.getByRole('button',{name:/^Retry Start week/i}));await flush();expect(nativeGet.call(localStorage,keys[0])).toBe('sunday');expect(router.state.location.pathname).toBe(pane);expect(ui.getByRole('dialog')).toBeTruthy();fireEvent.click(q.getByRole('button',{name:/^Retry Show Lunar/i}));await flush();expect(nativeGet.call(localStorage,keys[1])).toBe('false');expect(router.state.location.pathname).toBe(next);expect(ui.queryByRole('dialog')).toBeNull();});
it('a real held save protects navigation and releases after verified completion',async()=>{const {ui,q,router}=await host();const release=await hold(1);try{change(q,1);await flush();expect(nativeGet.call(localStorage,keys[1])).toBe('true');act(()=>{void router.navigate(next)});await flush();expect(router.state.location.pathname).toBe(pane);expect(ui.getByRole('dialog')).toBeTruthy();}finally{await release()}expect(nativeGet.call(localStorage,keys[1])).toBe('false');expect(router.state.location.pathname).toBe(next);});
it.each(['route','signout'])('epoch cancels old %s decision while fresh device draft still guards',async producer=>{const {ui,q,router}=await failed();let out:unknown='pending';act(()=>{if(producer==='route')void router.navigate(next);else void requestSettingsDeparture('sign-out').then(x=>out=x)});await flush();expect(ui.getByRole('dialog')).toBeTruthy();act(ownerB);await flush();expect(ui.queryByRole('dialog')).toBeNull();if(producer==='signout')expect(out).toBe(false);expect(router.state.location.pathname).toBe(pane);expect(q.getAllByRole('switch')[0].getAttribute('aria-checked')).toBe('false');act(()=>{void router.navigate('/app/dashboard')});await flush();expect(ui.getByRole('dialog')).toBeTruthy();fireEvent.click(dialog(ui).getByRole('button',{name:'Discard local changes and leave'}));await flush();expect(router.state.location.pathname).toBe('/app/dashboard');});
it('unmount cancels pending signout and removes unload warning',async()=>{const {ui}=await failed();let out:unknown='pending';act(()=>{void requestSettingsDeparture('sign-out').then(x=>out=x)});await flush();expect(out).toBe('pending');const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);expect(e.defaultPrevented).toBe(true);ui.unmount();await flush();expect(out).toBe(false);const after=new Event('beforeunload',{cancelable:true});window.dispatchEvent(after);expect(after.defaultPrevented).toBe(false);});
