import type { Lang } from "../types.js";

const COPY = {
  en: {
    title: "Time Tracker",
    tagline: "Start a category, pause when interrupted, and keep your day honest.",
    tracker: "Tracker",
    insights: "Insights",
    single: "Single",
    multi: "Multi",
    addRecord: "Add record",
    categories: "Categories",
    active: "Active sessions",
    today: "Today",
    week: "This week",
    goal: "goal",
    records: "Records",
    noRecords: "No records for this day yet.",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    end: "End",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    category: "Category",
    subcategory: "Subcategory",
    wholeCategory: "Whole category",
    note: "Note",
    startTime: "Start time",
    endTime: "End time",
    manualTitle: "Manual time record",
    distribution: "Where time went",
    sevenDays: "7-day trend",
    emptyInsights: "Track time to build insights.",
    running: "Running",
    dashboardTitle: "Time tracked",
    dashboardHint: "Open tracker",
  },
  zh: {
    title: "时间追踪",
    tagline: "点一下分类开始计时，中断时暂停，让每天的时间流向更清楚。",
    tracker: "追踪",
    insights: "洞察",
    single: "单任务",
    multi: "多任务",
    addRecord: "补录",
    categories: "分类",
    active: "进行中的计时",
    today: "今天",
    week: "本周",
    goal: "目标",
    records: "记录",
    noRecords: "这一天还没有记录。",
    start: "开始",
    pause: "暂停",
    resume: "继续",
    end: "结束",
    delete: "删除",
    cancel: "取消",
    save: "保存",
    category: "分类",
    subcategory: "子分类",
    wholeCategory: "整个分类",
    note: "备注",
    startTime: "开始时间",
    endTime: "结束时间",
    manualTitle: "补录时间",
    distribution: "时间都去哪了",
    sevenDays: "7 日趋势",
    emptyInsights: "开始记录后会生成洞察。",
    running: "计时中",
    dashboardTitle: "时间追踪",
    dashboardHint: "打开追踪",
  },
} as const;

export type CopyKey = keyof typeof COPY.en;

export function ttCopy(lang: Lang, key: CopyKey): string {
  return COPY[lang][key];
}
