import type { Lang } from "../types.js";

const COPY = {
  en: {
    title: "Time Tracker",
    tagline: "Start a category, pause when interrupted, and keep your day honest.",
    tracker: "Tracker",
    insights: "Insights",
    single: "Single",
    multi: "Multi",
    addRecord: "Add record",
    addSub: "Add subcategory",
    addWidget: "Add widget",
    adjustTime: "Adjust time",
    all: "All",
    avgPerDay: "Avg / day",
    breakdown: "Breakdown",
    byHour: "By hour",
    byWeekday: "By weekday",
    categories: "Categories",
    categoryCount: "categories",
    categoryRanking: "Category ranking",
    categoryMosaic: "Category mosaic",
    color: "Color",
    currentRunning: "Current running",
    dayTotal: "Day total",
    daysTracked: "Days tracked",
    decrease: "Decrease",
    deleteCategoryBody: "Delete %c and %n related records?",
    deleteEntryConfirm: "Delete this record?",
    deleteRange: "Delete range",
    deleteRangeBody: "Delete %n records in %r?",
    dateRange: "Date range",
    duration: "Duration",
    edit: "Edit",
    editCategory: "Edit category",
    editRecord: "Edit record",
    emptyBoard: "No insight cards.",
    exportCsv: "Export CSV",
    filters: "Filters",
    hideFilters: "Hide filters",
    hideInsightPreview: "Hide insight preview",
    hideRecords: "Hide records",
    hideSubcategories: "Hide subcategories",
    hideTimeStatus: "Hide time status",
    insightPreviewHidden: "Insights hidden",
    showInsightPreview: "Show",
    showRecords: "Show records",
    showSubcategories: "Show subcategories",
    showTimeStatus: "Show time status",
    timeStatus: "Time status",
    timeStatusHidden: "Time status hidden",
    addTimeStatusCard: "Add status card",
    removeTimeStatusCard: "Remove status card",
    restoreTimeStatusCard: "Restore card",
    noHiddenTimeStatusCards: "All status cards are visible.",
    customTimeStatus: "Custom time",
    customTimeName: "Name",
    customTimeTarget: "Target time",
    customTimePlaceholder: "Project deadline",
    targetTime: "Target",
    timeReached: "Reached",
    currentDate: "Current date",
    monthProgress: "Month progress",
    yearProgress: "Year progress",
    daysLeft: "days left",
    dayLeft: "day left",
    leftThisMonth: "left this month",
    leftThisYear: "left this year",
    todayRemaining: "Today remaining",
    noActiveTimer: "No active timer",
    readyToStart: "Start a category when ready.",
    active: "Active sessions",
    focusMode: "Focus mode",
    enterFocusMode: "Enter focus mode",
    exitFocusMode: "Exit fullscreen",
    focusTask: "Task",
    focusParentCategory: "Category",
    focusElapsed: "Elapsed",
    focusStartedAt: "Started",
    focusStatus: "Status",
    focusStopAndExit: "End and exit",
    today: "Today",
    todayTotal: "Today total",
    jumpToday: "Today",
    week: "This week",
    month: "This month",
    rangeWeek: "Week",
    rangeMonth: "Month",
    rangeYear: "Year",
    rangeCustom: "Custom",
    rangeAll: "All",
    goal: "goal",
    goalProgress: "Goal progress",
    goalToday: "Daily goal",
    heatmap: "Heatmap",
    peakHour: "Peak hour",
    hour: "Hour",
    bestDay: "Best day",
    increase: "Increase",
    longestSession: "Longest session",
    averageSession: "Average session",
    icon: "Icon",
    iconSearch: "Search icons",
    keepRunning: "Keep running",
    minute: "Minute",
    records: "Records",
    entries: "entries",
    entryOne: "entry",
    noRecords: "No records for this day yet.",
    noRecordsHint: "Start a category or add a manual record.",
    noSubcategories: "No subcategories yet.",
    name: "Name",
    namePlaceholder: "Category name",
    newCategory: "New category",
    noData: "No data yet",
    noneToday: "No time",
    pickSub: "Pick subcategory",
    quickStart: "Quick start",
    rangeSummary: "Range summary",
    recentSessions: "Recent sessions",
    removeWidget: "Remove widget",
    resetBoard: "Reset board",
    start: "Start",
    from: "From",
    to: "To",
    pause: "Pause",
    paused: "Paused",
    resume: "Resume",
    end: "End",
    stop: "End",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    second: "Second",
    category: "Category",
    subcategory: "Subcategory",
    wholeCategory: "Whole category",
    note: "Note",
    notePlaceholder: "Optional note",
    startTime: "Start time",
    endTime: "End time",
    timeRangeError: "End must be after start.",
    manualTitle: "Manual time record",
    distribution: "Where time went",
    donutRange: "Range split",
    subSplit: "Subcategory split",
    sevenDays: "7-day trend",
    thirtyDays: "30-day trend",
    focusRhythm: "Focus rhythm",
    emptyInsights: "Track time to build insights.",
    running: "Running",
    runningCount: "Running",
    singleSwitchBody: "Switch from %a to %b? The current timer will be ended.",
    switchAction: "Switch",
    whole: "Whole",
    dashboardTitle: "Time tracked",
    dashboardHint: "Open tracker",
  },
  zh: {
    title: "时间追踪",
    tagline: "点一下分类开始计时，中断时暂停，让每天的时间流向更清楚。",
    tracker: "追踪",
    insights: "洞察",
    single: "单任务",
    multi: "多任务",
    addRecord: "补录",
    addSub: "添加子分类",
    addWidget: "添加卡片",
    adjustTime: "调整时间",
    all: "全部",
    avgPerDay: "日均",
    breakdown: "明细",
    byHour: "按小时",
    byWeekday: "按星期",
    categories: "分类",
    categoryCount: "个分类",
    categoryRanking: "分类排行",
    categoryMosaic: "分类拼图",
    color: "颜色",
    currentRunning: "当前计时",
    dayTotal: "当日总计",
    daysTracked: "记录天数",
    decrease: "减少",
    deleteCategoryBody: "删除 %c 以及 %n 条相关记录？",
    deleteEntryConfirm: "删除这条记录？",
    deleteRange: "删除区间",
    deleteRangeBody: "删除 %r 内的 %n 条记录？",
    dateRange: "日期范围",
    duration: "时长",
    edit: "编辑",
    editCategory: "编辑分类",
    editRecord: "编辑记录",
    emptyBoard: "暂无洞察卡片。",
    exportCsv: "导出 CSV",
    filters: "筛选",
    hideFilters: "收起筛选",
    hideInsightPreview: "隐藏洞察预览",
    hideRecords: "收起记录",
    hideSubcategories: "收起子分类",
    hideTimeStatus: "隐藏时间状态",
    insightPreviewHidden: "洞察已隐藏",
    showInsightPreview: "显示",
    showRecords: "展开记录",
    showSubcategories: "展开子分类",
    showTimeStatus: "显示时间状态",
    timeStatus: "时间状态",
    timeStatusHidden: "时间状态已隐藏",
    addTimeStatusCard: "添加状态卡片",
    removeTimeStatusCard: "移除状态卡片",
    restoreTimeStatusCard: "恢复卡片",
    noHiddenTimeStatusCards: "全部状态卡片已显示。",
    customTimeStatus: "自定义时间",
    customTimeName: "名称",
    customTimeTarget: "目标时间",
    customTimePlaceholder: "例如：项目截止",
    targetTime: "目标",
    timeReached: "已到时间",
    currentDate: "当前日期",
    monthProgress: "本月进度",
    yearProgress: "今年进度",
    daysLeft: "天",
    dayLeft: "天",
    leftThisMonth: "距离月末",
    leftThisYear: "距离年末",
    todayRemaining: "今日剩余",
    noActiveTimer: "未计时",
    readyToStart: "准备好后点分类开始。",
    active: "进行中的计时",
    focusMode: "专注模式",
    enterFocusMode: "进入专注模式",
    exitFocusMode: "退出全屏",
    focusTask: "任务",
    focusParentCategory: "大分类",
    focusElapsed: "已计时",
    focusStartedAt: "开始时间",
    focusStatus: "当前状态",
    focusStopAndExit: "结束并退出",
    today: "今天",
    todayTotal: "今日总计",
    jumpToday: "回到今天",
    week: "本周",
    month: "本月",
    rangeWeek: "本周",
    rangeMonth: "本月",
    rangeYear: "今年",
    rangeCustom: "自定义",
    rangeAll: "全部",
    goal: "目标",
    goalProgress: "目标进度",
    goalToday: "每日目标",
    heatmap: "热力图",
    peakHour: "高峰小时",
    hour: "小时",
    bestDay: "最佳日期",
    increase: "增加",
    longestSession: "最长记录",
    averageSession: "平均记录",
    icon: "图标",
    iconSearch: "搜索图标",
    keepRunning: "保持计时中",
    minute: "分钟",
    records: "记录",
    entries: "条记录",
    entryOne: "条记录",
    noRecords: "这一天还没有记录。",
    noRecordsHint: "开始一个分类，或补录一段时间。",
    noSubcategories: "还没有子分类。",
    name: "名称",
    namePlaceholder: "分类名称",
    newCategory: "新建分类",
    noData: "暂无数据",
    noneToday: "暂无时间",
    pickSub: "选择子分类",
    quickStart: "快速开始",
    rangeSummary: "区间摘要",
    recentSessions: "最近记录",
    removeWidget: "移除卡片",
    resetBoard: "重置看板",
    start: "开始",
    from: "从",
    to: "到",
    pause: "暂停",
    paused: "已暂停",
    resume: "继续",
    end: "结束",
    stop: "结束",
    delete: "删除",
    cancel: "取消",
    save: "保存",
    second: "秒",
    category: "分类",
    subcategory: "子分类",
    wholeCategory: "整个分类",
    note: "备注",
    notePlaceholder: "可选备注",
    startTime: "开始时间",
    endTime: "结束时间",
    timeRangeError: "结束时间必须晚于开始时间。",
    manualTitle: "补录时间",
    distribution: "时间都去哪了",
    donutRange: "区间分布",
    subSplit: "子分类分布",
    sevenDays: "7 日趋势",
    thirtyDays: "30 日趋势",
    focusRhythm: "专注节奏",
    emptyInsights: "开始记录后会生成洞察。",
    running: "计时中",
    runningCount: "计时中",
    singleSwitchBody: "从 %a 切换到 %b？当前计时会被结束。",
    switchAction: "切换",
    whole: "整个分类",
    dashboardTitle: "时间追踪",
    dashboardHint: "打开追踪",
  },
} as const;

export type CopyKey = keyof typeof COPY.en;

export function ttCopy(lang: Lang, key: CopyKey): string {
  return COPY[lang][key];
}
