import React from './packages/plugin-web-board-workspaces/node_modules/react/index.js';
import {createRoot} from './packages/plugin-web-board-workspaces/node_modules/react-dom/client.js';
import {BoardWorkspacesModule} from './packages/plugin-web-board-workspaces/src/BoardWorkspacesModule.tsx';
import {TasksModule} from './packages/xai-web-tasks/src/TasksModule.tsx';
import {makeDefaultBoards} from './packages/plugin-web-board-core/src/internal/seed/board-data.ts';
import {SEED_TASK_COLS} from './packages/xai-web-tasks/src/internal/seed/tasksMock.ts';
import {accountScope} from './packages/plugin-web-storage/src/index.ts';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-tokens/src/layout.css';
import './packages/plugin-web-board-workspaces/src/styles.css';import './packages/xai-web-tasks/src/styles.css';
const NativeDate=Date;let now=NativeDate.parse('2026-05-23T12:00:00');
(globalThis as any).Date=class extends NativeDate{constructor(...args:any[]){super(...(args.length?args:[now]) as [any]);}static now(){return now}};
accountScope.activate(accountScope.lock('task02-native'),'one');
const boardKey=accountScope.physicalKey('xai_boards_v2'),taskKey=accountScope.physicalKey('xai_task_cols');
if(!localStorage.getItem(boardKey))localStorage.setItem(boardKey,JSON.stringify(makeDefaultBoards()));
if(!localStorage.getItem(taskKey))localStorage.setItem(taskKey,JSON.stringify(SEED_TASK_COLS.map(c=>({...c,tasks:[],completed:[],count:0}))));
const root=createRoot(document.getElementById('app')!);let view=0;
const show=(tasks=false)=>root.render(tasks?<TasksModule key={++view} lang="en"/>:<BoardWorkspacesModule key={++view} lang="en"/>);
const nativeSet=Storage.prototype.setItem;
(window as any).verify={show,boardKey,taskKey,boards:()=>JSON.parse(localStorage.getItem(boardKey)!),tasks:()=>JSON.parse(localStorage.getItem(taskKey)!).flatMap((c:any)=>[...c.tasks,...(c.completed??[])]),failTask:()=>{Storage.prototype.setItem=function(k,v){if(k===taskKey)throw new DOMException('synthetic quota','QuotaExceededError');nativeSet.call(this,k,v)}},restore:()=>{Storage.prototype.setItem=nativeSet},advance:()=>now+=86400000};show();
