import React from './packages/xai-web-tasks/node_modules/react/index.js';import {createRoot} from './packages/xai-web-tasks/node_modules/react-dom/client.js';
import {StatisticsModule} from './packages/plugin-web-statistics/src/StatisticsModule.tsx';import {TasksModule} from './packages/xai-web-tasks/src/TasksModule.tsx';
import {accountScope} from './packages/plugin-web-storage/src/index.ts';import {aggregateRange} from './packages/plugin-web-statistics/src/internal/aggregators.ts';import {EMPTY_HABITS_STATE} from './packages/plugin-web-statistics/src/internal/isHabitsStateRecord.ts';
import {SEED_TASK_COLS} from './packages/xai-web-tasks/src/internal/seed/tasksMock.ts';
import './packages/xai-web-tasks/src/styles.css';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-tokens/src/layout.css';import './packages/plugin-web-statistics/src/styles.css';
const NativeDate=Date;let clock=NativeDate.parse('2026-09-09T12:00:00');(globalThis as any).Date=class extends NativeDate{constructor(...args:any[]){super(...(args.length?args:[clock]) as [any])}static now(){return clock}};
accountScope.activate(accountScope.lock('completion-independent'),'g1');const key=accountScope.physicalKey('xai_task_cols');const root=createRoot(document.getElementById('app')!);let mount=0;
function route(kind='stats',lang='en'){root.render(React.createElement(kind==='tasks'?TasksModule:StatisticsModule,{lang,key:++mount}))}
function fixture(kind='undated'){if(kind==='calendar-invalid'){clock=NativeDate.parse('2026-10-09T12:00:00');localStorage.setItem(key,JSON.stringify([{tasks:[{done:true,completedAt:'2026-09-31T12:00:00Z'},{done:true,completedAt:'2026-10-01T10:00:00'},{done:true,completedAt:'2026-10-01T24:00:00Z'}]}]));route();return;}let tasks:any[]=[{done:true},{done:false,completedAt:'2026-09-08T10:00:00Z'}];let completed:any[]=[{}, {done:false}];if(kind==='mixed')tasks=[{done:true,completedAt:'2026-09-07T10:00:00Z'},{done:true,completedAt:'2026-09-08T10:00:00Z'},{done:true,completedAt:'2026-08-20T10:00:00Z'},{done:true},{done:true,completedAt:'invalid'},{done:true,completedAt:'2026-09-10T10:00:00Z'},{done:false,completedAt:'2026-09-09T10:00:00Z'}];localStorage.setItem(key,JSON.stringify([{id:'inbox',tasks,completed}]));route();}
function producer(){clock=NativeDate.parse('2026-09-09T12:00:00');const cols=SEED_TASK_COLS.map(c=>({...c,tasks:[],completed:[],count:0}));cols[3].tasks=[{id:'independent-task',title:{en:'Independent completion',zh:'独立完成任务'},done:false}];localStorage.setItem(key,JSON.stringify(cols));route('tasks');}
(window as any).probe={route,fixture,producer,setClock:(iso:string)=>{clock=NativeDate.parse(iso)},raw:()=>localStorage.getItem(key),agg:(range='week')=>aggregateRange(range,[],EMPTY_HABITS_STATE,0,new Date(clock),'en',JSON.parse(localStorage.getItem(key)??'[]'))};if(localStorage.getItem(key))route();else fixture();
