import React from './packages/xai-web-tasks/node_modules/react/index.js';import {createRoot} from './packages/xai-web-tasks/node_modules/react-dom/client.js';
import {StatisticsModule} from './packages/plugin-web-statistics/src/StatisticsModule.tsx';import {TasksModule} from './packages/xai-web-tasks/src/TasksModule.tsx';
import {accountScope} from './packages/plugin-web-storage/src/index.ts';import {aggregateRange} from './packages/plugin-web-statistics/src/internal/aggregators.ts';import {EMPTY_HABITS_STATE} from './packages/plugin-web-statistics/src/internal/isHabitsStateRecord.ts';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-tokens/src/layout.css';import './packages/plugin-web-statistics/src/styles.css';
const NativeDate=Date;let clock=NativeDate.parse('2026-09-09T12:00:00');(globalThis as any).Date=class extends NativeDate{constructor(...args:any[]){super(...(args.length?args:[clock]) as [any])}static now(){return clock}};
accountScope.activate(accountScope.lock('completion-independent'),'g1');const key=accountScope.physicalKey('xai_task_cols');const root=createRoot(document.getElementById('app')!);let mount=0;
function route(kind='stats',lang='en'){root.render(React.createElement(kind==='tasks'?TasksModule:StatisticsModule,{lang,key:++mount}))}
function fixture(kind='undated'){let tasks:any[]=[{done:true},{done:false,completedAt:'2026-09-08T10:00:00Z'}];let completed:any[]=[{}, {done:false}];if(kind==='mixed')tasks=[{done:true,completedAt:'2026-09-07T10:00:00Z'},{done:true,completedAt:'2026-09-08T10:00:00Z'},{done:true,completedAt:'2026-08-20T10:00:00Z'},{done:true},{done:true,completedAt:'invalid'},{done:true,completedAt:'2026-09-10T10:00:00Z'},{done:false,completedAt:'2026-09-09T10:00:00Z'}];localStorage.setItem(key,JSON.stringify([{id:'inbox',tasks,completed}]));route();}
(window as any).probe={route,fixture,raw:()=>localStorage.getItem(key),agg:(range='week')=>aggregateRange(range,[],EMPTY_HABITS_STATE,0,new Date(clock),'en',JSON.parse(localStorage.getItem(key)??'[]'))};fixture();
