import {describe,it,expect,vi} from 'vitest';
import {accountScope} from '@repo/plugin-web-storage';
import {commitTimeTrackerEntries,createTimeTrackerEntry,readTimeTrackerEntries,writeTimeTrackerEntries,TIME_TRACKER_ENTRIES_KEY,resumeTimeTrackerEntry} from '../internal/storage.js';
const raw=()=>localStorage.getItem(accountScope.physicalKey(TIME_TRACKER_ENTRIES_KEY));
const entry=()=>createTimeTrackerEntry('cat_work',null,1000,null,{en:'',zh:''});
describe('locked entry commands',()=>{
 it('refuses writes when Web Locks unavailable',async()=>{Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});await expect(commitTimeTrackerEntries([entry()],[],accountScope.capture())).rejects.toThrow('Web Locks');expect(raw()).toBeNull()});
 it('serializes fresh reads and rejects a second obsolete command snapshot',async()=>{let chain=Promise.resolve();Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_name:string,callback:()=>unknown)=>{const result=chain.then(callback);chain=result.then(()=>undefined,()=>undefined);return result}}});const scope=accountScope.capture();const results=await Promise.allSettled([commitTimeTrackerEntries([entry()],[],scope),commitTimeTrackerEntries([entry()],[],scope)]);expect(results.map(r=>r.status)).toEqual(['fulfilled','rejected']);expect(readTimeTrackerEntries()).toHaveLength(1)});
 it('enforces single mode under lock but allows distinct sessions in multi mode',async()=>{const first=entry();writeTimeTrackerEntries([first]);const next=entry();await expect(commitTimeTrackerEntries([first,next],[first],accountScope.capture())).rejects.toThrow('Single-task');localStorage.setItem('xai_tt_mode','multi');await commitTimeTrackerEntries([first,next],[first],accountScope.capture());expect(readTimeTrackerEntries()).toHaveLength(2)});
 it('retains malformed original bytes and refuses implicit repair',async()=>{const bad={...entry(),segments:[{start:1000,end:null},{start:2000,end:null}]};const bytes=' '+JSON.stringify([bad])+' ';localStorage.setItem(accountScope.physicalKey(TIME_TRACKER_ENTRIES_KEY),bytes);await expect(commitTimeTrackerEntries([],readTimeTrackerEntries(),accountScope.capture())).rejects.toThrow('recovery');expect(raw()).toBe(bytes)});
 it('revokes waiting A request after owner changes without writing either owner',async()=>{let release:()=>void=()=>{};Object.defineProperty(navigator,'locks',{configurable:true,value:{request:(_name:string,callback:()=>unknown)=>new Promise((resolve,reject)=>{release=()=>{try{resolve(callback())}catch(e){reject(e)}}})}});const aKey=accountScope.physicalKey(TIME_TRACKER_ENTRIES_KEY);const pending=commitTimeTrackerEntries([entry()],[],accountScope.capture());accountScope.activate(accountScope.lock('B'),'fixture');release();await expect(pending).rejects.toThrow();expect(localStorage.getItem(aKey)).toBeNull();expect(raw()).toBeNull()});
 it('failed native write leaves bytes intact and repeated resume is no-op',async()=>{const first=entry();writeTimeTrackerEntries([first]);const before=raw();const native=Storage.prototype.setItem;const fail=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this: Storage,k,v){if(k===accountScope.physicalKey(TIME_TRACKER_ENTRIES_KEY))throw new DOMException('quota','QuotaExceededError');native.call(this,k,v)});await expect(commitTimeTrackerEntries([{...first,note:{en:'draft',zh:'draft'}}],[first],accountScope.capture())).rejects.toThrow();expect(raw()).toBe(before);fail.mockRestore();const writes=vi.spyOn(Storage.prototype,'setItem');await commitTimeTrackerEntries(rows=>rows.map(row=>resumeTimeTrackerEntry(row,2000)),[first],accountScope.capture());expect(writes).not.toHaveBeenCalled();writes.mockRestore()});
});
