import {act,fireEvent,render,screen,within} from '@testing-library/react';
import {it,expect} from 'vitest';
import {TimeTrackerModule} from '../TimeTrackerModule.js';
import {createTimeTrackerEntry,writeTimeTrackerEntries,readTimeTrackerEntries} from '../internal/storage.js';
function source(){const now=Date.now();return {...createTimeTrackerEntry('cat_work',null,now-7200000,now-3000000,{en:'Precise source',zh:'精确记录'}),segments:[{start:now-7200000+125,end:now-6600000+875},{start:now-3600000+250,end:now-3000000+750}]}}
it('note-only edit keeps exact source intervals and their pause gap',async()=>{const original=source();writeTimeTrackerEntries([original]);render(<TimeTrackerModule lang="en"/>);fireEvent.click(within(document.querySelector('.tt-record-row')!).getByLabelText(/Edit/));expect(screen.getByLabelText('Start time')).toBeDisabled();fireEvent.change(screen.getByLabelText('Note'),{target:{value:'Metadata only'}});await act(async()=>{fireEvent.click(within(screen.getByRole('dialog')).getByText('Save'))});const row=readTimeTrackerEntries()[0]!;expect(row.segments).toEqual(original.segments);expect(row.note.en).toBe('Metadata only');expect(row.done).toBe(true)});
it('stale editor refuses overwrite and remains open with draft',async()=>{const original=source();writeTimeTrackerEntries([original]);render(<TimeTrackerModule lang="en"/>);fireEvent.click(within(document.querySelector('.tt-record-row')!).getByLabelText(/Edit/));fireEvent.change(screen.getByLabelText('Note'),{target:{value:'Unsubmitted draft'}});await act(async()=>{writeTimeTrackerEntries([{...original,note:{en:'Newer',zh:'Newer'}}])});await act(async()=>{fireEvent.click(within(screen.getByRole('dialog')).getByText('Save'))});expect(readTimeTrackerEntries()[0]!.note.en).toBe('Newer');expect(screen.getByLabelText('Note')).toHaveValue('Unsubmitted draft');expect(screen.getByRole('alert')).toHaveTextContent('changed while editing')});
it('single mode confirms switch and atomically ends old session before starting new',async()=>{render(<TimeTrackerModule lang="en"/>);await act(async()=>{fireEvent.click(document.querySelectorAll('.tt-category-start')[0]!)});await act(async()=>{fireEvent.click(document.querySelectorAll('.tt-category-start')[1]!)});expect(readTimeTrackerEntries()).toHaveLength(1);await act(async()=>{fireEvent.click(within(screen.getByRole('dialog')).getByText('End and start'))});expect(readTimeTrackerEntries()).toHaveLength(2);expect(readTimeTrackerEntries().filter(row=>!row.done)).toHaveLength(1)});
it('missing locks rejects manual Save visibly and retains editor draft',async()=>{Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});const original=source();writeTimeTrackerEntries([original]);render(<TimeTrackerModule lang="en"/>);fireEvent.click(within(document.querySelector('.tt-record-row')!).getByLabelText(/Edit/));fireEvent.change(screen.getByLabelText('Note'),{target:{value:'Keep this draft'}});await act(async()=>{fireEvent.click(within(screen.getByRole('dialog')).getByText('Save'))});expect(screen.getByRole('alert')).toHaveTextContent('Web Locks');expect(screen.getByLabelText('Note')).toHaveValue('Keep this draft');expect(readTimeTrackerEntries()[0]!.note.en).toBe('Precise source')});
