import {it,expect,vi} from 'vitest';
import {act,fireEvent} from '@testing-library/react';
import {accountScope} from '@repo/plugin-web-storage';
import {fixture,defaults,key,cases,mount,hold,flush,prefAlert,nativeSet,nativeGet,external,activate,timerBytes,captureExport,type Name} from './fixture';
fixture();
for(const row of cases){
 it(`${row.name}: actual control waits for its physical key lock; UI stays current and timer bytes remain separate`,async()=>{const ui=mount();await flush();const before=localStorage.getItem(key(row.name)),timer=timerBytes();const release=await hold(row.name);try{row.act(ui);await flush();expect.soft(localStorage.getItem(key(row.name))).toBe(before);expect(row.visible(ui)).toBe(true);}finally{await release();}expect(localStorage.getItem(key(row.name))).toBe(JSON.stringify(row.next));expect(timerBytes()).toEqual(timer);});
 it(`${row.name}: physical fault retains current choice and actual Retry persists only the unresolved intent`,async()=>{const ui=mount();await flush();const before=localStorage.getItem(key(row.name));const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key(row.name))throw Error('quota');nativeSet.call(this,k,v);});row.act(ui);await flush();expect(localStorage.getItem(key(row.name))).toBe(before);expect(row.visible(ui)).toBe(true);expect(prefAlert(ui)).not.toBeNull();spy.mockRestore();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(localStorage.getItem(key(row.name))).toBe(JSON.stringify(row.next));expect(row.visible(ui)).toBe(true);expect(prefAlert(ui)).toBeNull();});
}
it('invalid domains for all six remain byte-for-byte and expose preference recovery without default rewriting',async()=>{const bad:Record<Name,string>={preset:'"not-a-preset"',custom_minutes:'null',display_style:'{}',theme:'"plaid"',sound:'false',muted:'"false"'};for(const [name,raw]of Object.entries(bad))localStorage.setItem(key(name as Name),raw);const writes=vi.spyOn(Storage.prototype,'setItem');const ui=mount();await flush();for(const [name,raw]of Object.entries(bad)){expect.soft(localStorage.getItem(key(name as Name)),name).toBe(raw);expect.soft(writes.mock.calls.filter(c=>c[0]===key(name as Name)),name).toEqual([]);}expect(prefAlert(ui)).not.toBeNull();});
it('an unavailable theme read cannot seed its rendered fallback and shows preference recovery',async()=>{localStorage.setItem(key('theme'),'"blue"');vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,k){if(k===key('theme'))throw Error('read unavailable');return nativeGet.call(this,k);});const ui=mount();await flush();expect.soft(nativeGet.call(localStorage,key('theme'))).toBe('"blue"');expect(prefAlert(ui)).not.toBeNull();});
it('custom minutes partial success retries only failed minutes and preserves a newer successful-sibling preset',async()=>{const ui=mount();await flush();const fault=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key('custom_minutes'))throw Error('quota');nativeSet.call(this,k,v);});fireEvent.change(ui.getByTestId('custom-minutes-input'),{target:{value:'47'}});await flush();expect(localStorage.getItem(key('preset'))).toBe('"custom"');expect(localStorage.getItem(key('custom_minutes'))).toBe('45');expect(prefAlert(ui)).not.toBeNull();act(()=>external('preset','focus-30'));fault.mockRestore();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(localStorage.getItem(key('preset'))).toBe('"focus-30"');expect(localStorage.getItem(key('custom_minutes'))).toBe('47');});
it('a clean cross-document theme update projects without creating a write',async()=>{const ui=mount();await flush();const writes=vi.spyOn(Storage.prototype,'setItem');act(()=>external('theme','blue'));await flush();expect(ui.getByTestId('theme-blue').getAttribute('aria-pressed')).toBe('true');expect(writes.mock.calls.filter(c=>c[0]===key('theme'))).toEqual([]);});
it('dirty queued theme keeps local selection but refuses an external replacement and Retry cannot overwrite it',async()=>{const ui=mount();await flush();const release=await hold('theme');try{fireEvent.click(ui.getByTestId('theme-blue'));await flush();act(()=>external('theme','violet'));}finally{await release();}expect(localStorage.getItem(key('theme'))).toBe('"violet"');expect(ui.getByTestId('theme-blue').getAttribute('aria-pressed')).toBe('true');expect(prefAlert(ui)).not.toBeNull();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(localStorage.getItem(key('theme'))).toBe('"violet"');});
it('uncertain unchanged theme Retry verifies one physical write and does not fake Saved early',async()=>{const ui=mount();await flush();let armed=false,writes=0;vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){nativeSet.call(this,k,v);if(k===key('theme')){armed=true;writes++;}});vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,k){if(k===key('theme')&&armed){armed=false;throw Error('readback');}return nativeGet.call(this,k);});fireEvent.click(ui.getByTestId('theme-blue'));await flush();expect(nativeGet.call(localStorage,key('theme'))).toBe('"blue"');expect(prefAlert(ui)).not.toBeNull();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(prefAlert(ui)).toBeNull();expect(writes).toBe(1);});
it('pending device theme survives A to B to locked account with the same key and newest local selection',async()=>{const ui=mount();await flush();const release=await hold('theme');try{fireEvent.click(ui.getByTestId('theme-blue'));fireEvent.click(ui.getByTestId('theme-violet'));act(()=>activate('pomo-astra-B'));act(()=>accountScope.lock('locked'));}finally{await release();}expect(localStorage.getItem(key('theme'))).toBe('"violet"');expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');expect(prefAlert(ui)).toBeNull();});
it('two rapid mute clicks retain the latest false choice after a queued first toggle',async()=>{const ui=mount();await flush();const release=await hold('muted');try{fireEvent.click(ui.getByTestId('mute-btn'));fireEvent.click(ui.getByTestId('mute-btn'));expect(ui.getByTestId('mute-btn').getAttribute('aria-label')).toBe('Mute');}finally{await release();}expect(localStorage.getItem(key('muted'))).toBe('false');expect(prefAlert(ui)).toBeNull();});
it('partial preference export is actual latest six-value JSON and download setup failure retains choices',async()=>{const ui=mount();await flush();vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key('theme'))throw Error('quota');nativeSet.call(this,k,v);});for(const row of cases)row.act(ui);fireEvent.click(ui.getByTestId('theme-violet'));await flush();const read=captureExport();fireEvent.click(ui.getByRole('button',{name:'Export current preferences'}));expect(await read()).toEqual({version:1,kind:'pomodoro-preference-draft',values:{preset:'custom',customMinutes:47,displayStyle:'minimal',theme:'violet',sound:'bell',muted:true}});vi.spyOn(URL,'createObjectURL').mockImplementation(()=>{throw Error('download setup');});fireEvent.click(ui.getByRole('button',{name:'Export current preferences'}));expect(ui.getByText('Preference export failed. Please retry.')).toBeTruthy();expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');expect(prefAlert(ui)).not.toBeNull();});
it('ordinary theme conflict offers explicit reload/discard and adopts the external value only by that user choice',async()=>{const ui=mount();await flush();const release=await hold('theme');try{fireEvent.click(ui.getByTestId('theme-blue'));act(()=>external('theme','violet'));}finally{await release();}expect(localStorage.getItem(key('theme'))).toBe('"violet"');expect(prefAlert(ui)).not.toBeNull();const recover=ui.queryByRole('button',{name:/reload|discard/i});expect(recover,'ordinary conflict needs an explicit recovery choice').not.toBeNull();fireEvent.click(recover!);await flush();expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');expect(localStorage.getItem(key('theme'))).toBe('"violet"');expect(prefAlert(ui)).toBeNull();});
it('reloading repaired invalid sound cannot discard unrelated latest failed theme draft or its retry',async()=>{localStorage.setItem(key('sound'),'null');const ui=mount();await flush();const fault=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,k,v){if(k===key('theme'))throw Error('theme quota');nativeSet.call(this,k,v);});fireEvent.click(ui.getByTestId('theme-blue'));await flush();fireEvent.click(ui.getByTestId('theme-violet'));await flush();expect(ui.getByTestId('theme-violet').getAttribute('aria-pressed')).toBe('true');expect(localStorage.getItem(key('theme'))).toBe('"coral"');nativeSet.call(localStorage,key('sound'),'"bell"');fireEvent.click(ui.getByRole('button',{name:/reload/i}));await flush();expect.soft((ui.getByTestId('sound-select') as HTMLSelectElement).value).toBe('bell');expect.soft(ui.getByTestId('theme-violet').getAttribute('aria-pressed'),'unrelated unsaved choice must survive sound reread').toBe('true');expect(prefAlert(ui)).not.toBeNull();fault.mockRestore();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(localStorage.getItem(key('theme'))).toBe('"violet"');expect(localStorage.getItem(key('sound'))).toBe('"bell"');});
it('rejected native lock Promise becomes visible retryable preference failure without fallback write',async()=>{const ui=mount();await flush();const request=navigator.locks.request.bind(navigator.locks);vi.spyOn(navigator.locks,'request').mockImplementation(((name:string,...args:any[])=>name.includes(encodeURIComponent(key('theme')))?Promise.reject(Error('lock rejected')):(request as any)(name,...args)) as any);fireEvent.click(ui.getByTestId('theme-blue'));await flush();expect(localStorage.getItem(key('theme'))).toBe('"coral"');expect(ui.getByTestId('theme-blue').getAttribute('aria-pressed')).toBe('true');expect(prefAlert(ui)).not.toBeNull();vi.restoreAllMocks();fireEvent.click(ui.getByRole('button',{name:'Retry preferences'}));await flush();expect(localStorage.getItem(key('theme'))).toBe('"blue"');expect(prefAlert(ui)).toBeNull();});
