import React from './packages/xai-web-tasks/node_modules/react/index.js';import {createRoot} from './packages/xai-web-tasks/node_modules/react-dom/client.js';
import {TasksModule} from './packages/xai-web-tasks/src/TasksModule.tsx';import {HabitsModule} from './packages/xai-web-habits/src/HabitsModule.tsx';import {CalendarModule} from './packages/xai-web-calendar/src/CalendarModule.tsx';import {StatisticsModule} from './packages/plugin-web-statistics/src/StatisticsModule.tsx';import {MetricTrackerModule} from './packages/plugin-web-metric-tracker/src/MetricTrackerModule.tsx';import {TimeTrackerModule} from './packages/plugin-web-time-tracker/src/TimeTrackerModule.tsx';
import {accountScope} from './packages/plugin-web-storage/src/index.ts';import {SEED_TASK_COLS} from './packages/xai-web-tasks/src/internal/seed/tasksMock.ts';import {createSeedMetricTrackerState} from './packages/plugin-web-metric-tracker/src/internal/seed.ts';
import './packages/plugin-web-tokens/src/tokens.css';import './packages/plugin-web-statistics/src/styles.css';import './packages/plugin-web-metric-tracker/src/styles.css';import './packages/plugin-web-time-tracker/src/styles.css';
const NativeDate=Date;let instant=new NativeDate(2026,8,12,23,59,59).getTime();(globalThis as any).Date=class extends NativeDate{constructor(...args:any[]){super(...(args.length?args:[instant]) as [any])}static now(){return instant}};
accountScope.activate(accountScope.lock('six-consumers'),'g1');const key=(k:string)=>accountScope.physicalKey(k);
const cols=SEED_TASK_COLS.map(c=>({...c,tasks:[],completed:[],count:0}));cols[3].tasks=[{id:'tomorrow',title:{en:'Sunday due task',zh:'Sunday due task'},dueDate:'2026-09-13'},{id:'completed',title:{en:'Saturday done',zh:'Saturday done'},done:true,completedAt:new NativeDate(2026,8,12,12).toISOString()}] as any;localStorage.setItem(key('xai_task_cols'),JSON.stringify(cols));
localStorage.setItem(key('xai_tt_entries_v2'),'[]');
const metric=createSeedMetricTrackerState();metric.records=[{id:'tomorrow-weight',metricId:'weight',value:71,unit:'kg',measuredAt:new NativeDate(2026,8,13,8).toISOString(),createdAt:new NativeDate().toISOString(),updatedAt:new NativeDate().toISOString(),note:'Sunday measurement'}];localStorage.setItem(key('xai_metric_tracker_state_v1'),JSON.stringify(metric));
for(const [id,Module] of Object.entries({tasks:TasksModule,habits:HabitsModule,calendar:CalendarModule,stats:StatisticsModule,metrics:MetricTrackerModule,tt:TimeTrackerModule})){const div=document.createElement('section');div.id=id;document.body.append(div);createRoot(div).render(React.createElement(Module as any,{lang:'en'}))}
(window as any).probe={advance:()=>{instant=new NativeDate(2026,8,13,0,0,1).getTime()},resume:(event:string)=>window.dispatchEvent(new Event(event)),read:()=>({habits:document.querySelector('#habits .weekday.today .wd-num')?.textContent,calendar:(document.querySelector('#calendar .cal-day.today') as HTMLElement)?.dataset.date,stats:document.querySelector('#stats [data-testid=tasks-barchart-marker]')?.closest('.stats-chart')?.textContent,metrics:document.querySelector('#metrics .mt-record-groups')?.textContent,tt:document.querySelector('#tt .tt-time-card')?.textContent,tasks:document.querySelector('#tasks .tasks-board')?.textContent??document.querySelector('#tasks')?.textContent})};
